### ISSUE TITLE
'default' face isn't taken in account when autoface-mode is off

### ISSUE THREAD

**Issue by kaofelix** [aquamacs-emacs/aquamacs-emacs#10]
If I turn off autoface-mode every face on aquamacs become Lucida Grande, even with the default face explicitly set to Monaco. The most odd part is that even the customization preview for the default face - the (sample) thing on the custom interface for faces - is rendered using Lucida Grande, ignoring all settings. I have the impression that aquamacs is getting the default face from somewhere outside it (maybe from some cocoa stuff, but I don't know cocoa so I'm just guessing here) or from some other customization parameter that I can't find.

**Comment by davidswelt** [comment]
fixed, thanks again.
