### ISSUE TITLE
AUCTeX 11.88 is available

### ISSUE THREAD

**Issue by giordano** [aquamacs-emacs/aquamacs-emacs#100]
A new version of AUCTeX [has been released](http://lists.gnu.org/archive/html/info-gnu/2014-10/msg00019.html).  There have been quite a few new features, it may be worth to update the version of AUCTeX bundled with Aquamacs.

**Comment by davidswelt** [comment]
Thanks for the note.  AUCTeX releases are rare, so this is big news.  Congratulations.
I’m going to work on this pronto.

**Comment by davidswelt** [comment]
AUCTeX 11.88 is included in Aquamacs 3.2.
