### ISSUE TITLE
Tramp hangs if no local files are open.

### ISSUE THREAD

**Issue by brorfred** [aquamacs-emacs/aquamacs-emacs#103]
Running nightly build from Nov 20. Aquamacs hangs every time when I try to open a file via TRIM as the first file. Get's stuck at Tramp: Inserting '/scp:server:/path/to/file/file.py' ...done. It works fine if I open a local file first...

<img width="507" alt="screen shot 2015-11-20 at 16 28 21" src="https://cloud.githubusercontent.com/assets/832870/11313162/e0c50184-8fa8-11e5-9a95-d02eca42dfef.png">

**Comment by davidswelt** [comment]
Hi Bror,

I’m sorry, I don’t know what TRIM is.  Is this some mode?
I would need precise, step by step directions.

Or did you mean TRAMP, spell-corrected to TRIM?
- David

**Comment by brorfred** [comment]
Oops, yes, I meant Tramp. Thanks for looking into this! Let me know how I can help.

**Comment by davidswelt** [comment]
So, if I do the same, but with ssh: instead of scp: as a method, it no longer hangs.

The hang with scp: does resolve itself after a minute.  Does it do the same for you?

**Comment by davidswelt** [comment]
Hang is in Faccept_process_output and wait_reading_process_output.

Hang lasts for about 1 minute, cannot be broken with C-g.

Also, hang when killing the buffer:

Emacs.app/Contents/MacOS/Emacs -q /scp:dr@xxx:/Users/dr/.emacs
(loads without the wait.  Press C-x C-c and experience a long delay with no output.)

**Comment by davidswelt** [comment]
Reproduces reliably with Aquamacs -q, but not with -Q.  Not with plain GNU Emacs 25.1 without configuration.   Also not with Aquamacs-Q and then (aquamacs-setup).

setting tramp-verbose to 10,  no interesting info.

**Comment by davidswelt** [comment]
This no longer reproduces in Aquamacs 3.3.
Thank you for the report.
