### ISSUE TITLE
left margin too small to see the line numbers

### ISSUE THREAD

**Issue by dpk** [aquamacs-emacs/aquamacs-emacs#104]
Enabled through Options &rarr; View &rarr; Line Numbering.

![too small margin](https://i.imgur.com/O0BNe0M.png)

I've tried setting left-margin-width etc. and no luck.

**Comment by davidswelt** [comment]
This works quite well for me.  I would need precise instructions on how to produce this (i.e., start up a nightly build without customizations, then describe configuration necessary to produce the effect).

With that I should be able to address the issue.

**Comment by dpk** [comment]
I was using Aquamacs 3.2 stable. Now trying a nightly

**Comment by dpk** [comment]
Okay, this works in the nightly. Just not in the stable release.
