### ISSUE TITLE
anti-aliasing settings not working

### ISSUE THREAD

**Issue by dpk** [aquamacs-emacs/aquamacs-emacs#105]
OS X 10.11.

Tried `ns-antialias-text` as `nil`, `mac-allow-anti-aliasing` as `nil`, and various low values for the `org.gnu.AquamacsEmacs AppleAntiAliasingThreshold` defaults preference.

Monaco 9 is still rendering with anti-aliasing.

**Comment by davidswelt** [comment]
I can’t reproduce.

(setq ns-antialias-text nil)

will make all text grainy, as expected.

Perhaps try out starting without customizations.  Also, use a more recent build from http://aquamacs.org/nightlies.shtml if you’re not doing that already.
- David

**Comment by dpk** [comment]
Okay, I upgraded to a nightly. Now `ns-antialias-text` works (though characters are spaced too close together), but `org.gnu.AquamacsEmacs AppleAntiAliasingThreshold` still doesn’t. What unit is the size measured in? Points? Pixels? That’s not documented anywhere.

**Comment by davidswelt** [comment]
As there is a lisp-level variable, AppleAntiAliasingThreshold is not supported.  Even some Apple applications like Keynote seem to ignore it.
