### ISSUE TITLE
excessive CPU usage

### ISSUE THREAD

**Issue by vancleve** [aquamacs-emacs/aquamacs-emacs#107]
In the most recent nightly, I'm experiencing excessive CPU usage that often leads to a spinning beach ball and crash. This appears to happen in certain edit modes (HTML/markdown/etc) and may be related to this isssue: https://groups.google.com/forum/#!topic/aquamacs-devel/hK5TfxlbAqk

Running the most recent compiled nightly (March 29th) with `Aquamacs -q` and loading the `.html` file from http://www.aquamacs.org, I get ~30% CPU usage with the file simply open, which is very high compared to less than 1% for Aquamacs 3.2. I've run the profiler after loading the `.html` file and observing high CPU usage and have pasted the results below, though I'm not sure they're very helpful.

```
- redisplay_internal (C function)                                1696  71%
 - or                                                            1576  66%
  - and                                                          1572  66%
   - or                                                          1570  66%
    - not                                                        1553  65%
     - verify-visited-file-modtime                                101   4%
      + ucs-normalize-hfs-nfd-pre-write-conversion                 67   2%
      + replace-buffer-in-windows                                  10   0%
      + tabbar-window-track-killed                                  3   0%
      + delete-window-if-one-buffer-one-frame                       2   0%
      + html-helper-remove-buffer                                   1   0%
        process-kill-buffer-query-function                          1   0%
        uniquify-kill-buffer-function                               1   0%
    + and                                                          16   0%
  + not                                                             3   0%
   menu-bar-update-buffers                                         28   1%
 + eval                                                            26   1%
 + jit-lock-function                                               14   0%
   tool-bar-make-keymap                                            12   0%
 + maybe-restore-tool-bar-configuration                            11   0%
 + keymap-canonicalize                                              8   0%
 + #<compiled 0x40c0da0d>                                           6   0%
 + aquamacs-update-menu                                             2   0%
   and                                                              1   0%
- ...                                                             521  21%
   Automatic GC                                                   520  21%
 + run-hooks                                                        1   0%
+ command-execute                                                  78   3%
+ timer-event-handler                                              76   3%
```

**Comment by davidswelt** [comment]
Thank you.  We’ve been trying to debug this.

I will change the nightly builds and ask you to try that.

Where did you get the lisp-level profile you posted below?

D

**Comment by vancleve** [comment]
Ok, sounds good.

I got the profile with `M-x profiler-start`, `cpu mode`, then `M-x profiler-report`

**Comment by cybersquid** [comment]
I'm seeing this too with the 4/1 nightly.  Sitting idle on an org-mode document the CPU utilization is 99.9% (see attached image).  Unfortunately aquamacs is unresponsive so I can't harvest the profile report.
![emacs-runaway](https://cloud.githubusercontent.com/assets/2079053/14219147/731aea9a-f80d-11e5-815a-31af491dc5ba.png)

**Comment by davidswelt** [comment]
Please try the new nightly build!

**Comment by vancleve** [comment]
Dang, still seeing excessive CPU usage in both HTML or markdown modes where I had observed it before (2016-04-03 build).

**Comment by rpgoldman** [comment]
I'm afraid I just saw the excessive CPU usage again, myself.  Once again, after an invocation of emacsclient.

I have a spindump, if another one would help.

**Comment by davidswelt** [comment]
a little frustrating.   OK.

**Comment by davidswelt** [comment]
I think that this issue has been fixed with recent commits c622e9 and d4f77e.
Please let me know if you still experience the hangs, and feel free to re-open this issue in case you do.
