### ISSUE TITLE
why aquamacs auctex can get a high DPI equation preview but GNU Emacs can't?

### ISSUE THREAD

**Issue by kirchhoff** [aquamacs-emacs/aquamacs-emacs#108]
I am using Aqumacs 3.2 and GNU Emacs 25.0.92.1 in retina osx EI .
The equation's preview GNU Emacs , and Aquamacs  like below:
![image](https://cloud.githubusercontent.com/assets/2253887/14764928/6446889c-09fd-11e6-8afb-a4144c128876.png)

![image](https://cloud.githubusercontent.com/assets/2253887/14764929/72f1de28-09fd-11e6-8204-2165031d91a1.png)

I reused the Aqumacs's modified auctex packages for my own GNU Emacs ,I have debuged the elisp source code,I find that this two versions emacs generate the same size png for the same equation ,and both of them have the low DPI, the png's path like this "$HOME/_region_.prv/tmp73138HGb/pr1-1.png"

How aquamacs can show the high DPI equation preview within the low DPI pns?Do I missed anythong?Thank you very much

**Comment by davidswelt** [comment]
Aquamacs has modifications at the C level, not just in Lisp, to allow it to make use of Retina displays.

## 

http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by kirchhoff** [comment]
Oh, I see. That's why. Thank you very much！
