### ISSUE TITLE
Scrollbar glitches when entering and exiting fullscreen mode

### ISSUE THREAD

**Issue by kaofelix** [aquamacs-emacs/aquamacs-emacs#11]
Everytime I enter and exit fullscreen I see some scrollbars flashing in the middle of the frame and disappearing afterwards. The number of scrollbars seems to be incrementing everytime I repeat the operation. Also, if I move to a different space (from the mac spaces feature) and back to the space I was in I can see them standing on my frame. After do some scrolling on the frame the scrollbars disappear, but they still flicker from time to time. I've put an screenshot showing the problem here: http://www.inf.ufrgs.br/~kcfelix/arquivos/aquamacs-bug.png.

**Comment by davidswelt** [comment]
The recent re-write of fullscreen mode has addressed the issue.

**Comment by kaofelix** [comment]
Wow, the new fullscreen is awesome! Thanks for that :)
