### ISSUE TITLE
restore filladapt

### ISSUE THREAD

**Issue by nega0** [aquamacs-emacs/aquamacs-emacs#110]
Can `filladapt.el` be restored, but maybe disabled by default? Some old-timers like myself prefer it to _adaptive-fill_.

re: bfcedf33e4ddee6772bcd23741536d52f25bcb45 &  731c649bb3f9de4e90d841ac49a8e373babad96a

**Comment by davidswelt** [comment]
We may be able to include it, so all you have to do is (require ‘filladapt).
Would that work for you?

**Comment by nega0** [comment]
Perfect.

**Comment by davidswelt** [comment]
done
