### ISSUE TITLE
Aquamacs Emacs Macbook Pro Power Consumption

### ISSUE THREAD

**Issue by artforlife** [aquamacs-emacs/aquamacs-emacs#114]
Whenever I launch Aquamacs (Emacs) on my 2015 Macbook Pro, I begin hearing the fan run intensely after about 5 minutes. When I click on the battery icon in the menu bar, it tell me that Aquamacs is using significant energy. Is there a way to prevent this? I tried installing the newest version of the software but it behaves the same.

**Comment by davidswelt** [comment]
This was a bug that we fixed quite some time ago.  Can you try starting Aquamacs without customizations (Help->Diagnose menu)?  Make sure to check which process (you will have 2) is using CPU.

**Comment by artforlife** [comment]
Several restarts and a re-install seem to have solved this for me. I am still unsure of the cause.
