### ISSUE TITLE
modeline, echo area fall outside frame when toolbar enabled

### ISSUE THREAD

**Issue by nathaniel** [aquamacs-emacs/aquamacs-emacs#12]
If Aquamacs starts (even -Q) with toolbar not shown, then turning on the toolbar in a frame that covers nearly the full extent of the screen results in a frame that lacks the modeline and echo area.  Any resizing of frame, or toggling toolbar, or minibuffer input causes the minibuffer to reappear.

Calling `smart-move-frame-inside-screen' following ns-toggle-toolbar (e.g. within an idle timer) corrects the issue, but isn't appropriate for all cases.

**Comment by maehne** [comment]
This issue is still present in Aquamacs 2.4 on at least OS X Lion and Mountain Lion.

**Comment by HayoBaan** [comment]
I don't understand the issue, for me Aquamacs always starts with a toolbar. Can you describe how this can be reproduced on the latest version of Aquamacs?

**Comment by treese** [comment]
Looking at old bugs: I could not reproduce this in the current build or distributed version.
