### ISSUE TITLE
`frame-iconified-p` not fbound

### ISSUE THREAD

**Issue by krono** [aquamacs-emacs/aquamacs-emacs#123]
At least these use `frame-iconified-p`:

 <https://github.com/davidswelt/aquamacs-emacs/blob/aquamacs3/aquamacs/src/site-lisp/macosx/osx_defaults.el#L151>
  <https://github.com/davidswelt/aquamacs-emacs/blob/aquamacs3/aquamacs/src/site-lisp/one-buffer-one-frame.el#L696>

But `frame-iconified-p` has been renamed to `frcmds-frame-iconified-p`, alongside others three years ago:

 <https://github.com/davidswelt/aquamacs-emacs/blob/aquamacs3/aquamacs/src/site-lisp/oneonone/frame-cmds.el#L143>

**Comment by davidswelt** [comment]
Thank you.  Fixed, and checked other renamed functions.

**Comment by krono** [comment]
yay!
