### ISSUE TITLE
what is the equivalent command to run aquamacs through terminal

### ISSUE THREAD

**Issue by kirk86** [aquamacs-emacs/aquamacs-emacs#131]
In emacs we have `emacs -nw` and beautifully you can work with emacs from your favorite terminal client. I would like to know what is the equivalent for `aquamacs`. I've been searching all day and couldn't find a solution.

**Comment by sidney** [comment]
Read up on Command Line Tools, https://www.emacswiki.org/emacs/AquamacsFAQ#toc24

Once you install command line tools, the emacs command from the Terminal command will invoke the emacs that is in aquamacs instead of the system emacs, with emacs -nw working as you are used to.

**Comment by kirk86** [comment]
@sidney thanks.
