### ISSUE TITLE
ipython3 with aquamcs

### ISSUE THREAD

**Issue by jiamo** [aquamacs-emacs/aquamacs-emacs#132]
When I set `(setq py-shell-name "ipython3")` and using `^-C ^-C (ctrl-C ctrl-C)` to  compile and run a python file. It pip something like:

![image](https://user-images.githubusercontent.com/732751/31113064-15472a7e-a7dd-11e7-946b-78f44ce1cc63.png)

And start a tk-python outside aquamcs.
While  `(setq py-shell-name "python3")` is working fine.

I remember If I don't install `matplotlib` it  won't start.

**Comment by davidswelt** [comment]
I would recommend asking on the Emacs on OSX mailing list first.  I’m not sure this is an Aquamacs-specific problem as opposed to one with python mode of Emacs in general.  I will leave this bug open for now until we know more.


--
http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by ElderDelp** [comment]
Python3 is a command line interface (line oriented)
Ipython3 is a gui (graphical user interface). It will launch and control a new set of Windows.
So, 'working as designed' would be my conclusion.
 try the iOS, emacs, or Python user forums, I find that the
I agree with David's assessment, if this does not address your concern,
Try the iOS, Python, or emacs user forums.

/g

On Oct 3, 2017, at 1:52 AM, jiamo <notifications@github.com<mailto:notifications@github.com>> wrote:


When I set (setq py-shell-name "ipython3") and using ^-C ^-C (ctrl-C ctrl-C) to compile and run a python file. It pip something like:

[image]<https://user-images.githubusercontent.com/732751/31113064-15472a7e-a7dd-11e7-946b-78f44ce1cc63.png>

And start a tk-python outside aquamcs.
While (setq py-shell-name "python3") is working fine.

**Comment by jiamo** [comment]
OK . I give up on default python-mode and change to elpy.

The ipython work fine. (May be aquamacs can using elpy as default no the python-mode)

**Comment by appetrosyan** [comment]
Same here. Setting and re-setting colors in ipython and or setting command line arguemtns didn't work
