### ISSUE TITLE
a question about how to automatic install package.

### ISSUE THREAD

**Issue by jiamo** [aquamacs-emacs/aquamacs-emacs#134]
At now I install package by `option/Manage Emacs Pacakge`.  And do something config for it. like [https://github.com/jiamo/aquamacs-config](https://github.com/jiamo/aquamacs-config).

If I need set up another computer. I don't want install the package again by hand. 
How can I do it automatic?

Something I can put in my .emacs file. So in new computer it can auto install it if it don't have the packge?

**Comment by davidswelt** [comment]
Please ask your questions on the support mailing list (Emacs on OSX). This is the bug tracker.
