### ISSUE TITLE
Cannot install Packages

### ISSUE THREAD

**Issue by g3ntleman** [aquamacs-emacs/aquamacs-emacs#149]
I have a vanilla Aquamacs, no customizations.el, no .emacs file.

I create a -emacs file with just:

---------------------
;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
;;(add-to-list 'package-archives (cons "melpa" "http://melpa.org/packages/") t)
(add-to-list 'package-archives (cons "melpa-stable" "http://stable.melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives (cons "gnu" "https://elpa.gnu.org/packages/")))

(package-initialize)
---------------
I'm using Options->Manage Emacs Packages

to get a list of available packages. These gets downloaded from melpa etc. and displayed.

I klick on e.g. "neotree". It opens a details buffer for neotree (so far, so good).

I hit "Install" and it fails with the following errors from *messages*:

Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 stable.melpa.org --protocols ssl3’...failed
Opening TLS connection to ‘stable.melpa.org’...failed
package-install-from-archive: Could not create connection to stable.melpa.org:443

So I cannot install packages. I tried manually using M-x package-install, but it fails the same way.

Mainline Emacs does not have this problem.

**Comment by treese** [comment]
This is an unfortunate collision of changes in MELPA, the main Emacs code, and what ships on Mac OS.

The easiest thing if you happen to use Home-brew is to install gnutls:

brew install gnutls

and then add the following to your Emacs configuration:

(with-eval-after-load 'tls
(push "/private/etc/ssl/cert.pem" gnutls-trustfiles))

There is a long discussion in the Aquamacs GitHub issue tracker: https://github.com/davidswelt/aquamacs-emacs/issues/133, but most of it is about how to fix the Aquamacs distribution. As  David mentioned, we’re hoping to have that done soon. 

If you aren’t using Homebrew, or if you want to know more about what went wrong, feel free to ask.

Best,

Win

**Comment by FrankDMartinez** [comment]
@treese It's been almost two years since you said you were "hoping to have that done soon". Any updates? I ask because I am experiencing the same problem.

**Comment by treese** [comment]
@FrankDMartinez Which version are you using? Which version of Mac OS? Aquamacs 3.5 included the fixes referred to here and in #133, although there have been some reports of problems that appear similar.

Did this just start happening for you? What is the exact error message you are getting?

**Comment by FrankDMartinez** [comment]
@treese My apologies. I misread the message originally quoted. I am having a different issue, for which I can create a separate entry.

**Comment by treese** [comment]
I believe that this one was fixed as of the gnutls fixed in Aquamacs 3.5. If that's not the case, please reopen this issue.

**Comment by eskonuutila** [comment]
Hi!

I'm not able to install melpa packages anymore. I've had this same issue a couple of times before and then found instructions to overcome the problem, but no luck this time. I'm running macOS BigSur 11.2.3. To fix the issue:

* I moved away all my own emacs definitions

* Deleted all Aquamacs related stuff in `~/Library`

* Reinstalled Aquamacs (Aquamacs 3.5  GNU Emacs 25.3.50.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G2016)) dated 2019-08-18 rev. 70b7398da506a9a53867909fa12e5cb3a07ba5c9 Copyright (C) 2017 Free Software Foundation, Inc.).

* Added into my `Library/Preferences/Aquamacs\ Emacs/Preferences.el` the definitions above  in  the messages of g3ntleman (commented on 12 Mar 2019) and  treese (commented on 12 Mar 2019) 

* I did `brew reinstall gnutls`.

Still, `M-x list-packages` is not able to retrieve melpa packages. `*Messages*` contains:

`error in process filter: Error retrieving: https://stable.melpa.org/packages/archive-contents (error http 400) [2 times]`

My `Library/Preferences/Aquamacs\ Emacs/Preferences.el` is:

```
(require 'package)
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

(setenv "PATH" (concat "~/bin.sh:/usr/local/bin:" (getenv "PATH")))`
(require 'tls)
(with-eval-after-load 'tls
  (unless (boundp 'gnutls-trustfiles)
    (setq gnutls-trustfiles nil))
  ;; (push "/usr/local/etc/libressl/cert.pem" gnutls-trustfiles) ;; Does not work
  (push "/private/etc/libressl/cert.pem" gnutls-trustfiles)
  )
(setq tls-checktrust 'ask)
```

Any ideas what could be wrong?

**Comment by treese** [comment]
Hi, Esko. Try adding the line

``` (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")```

inside the `with-eval-after-load`. This works around a protocol version problem.

This will be working out of the box in the upcoming Aquamacs. 3.6 release.

**Comment by eskonuutila** [comment]
Thanks, seems to work!

**Comment by michaeljanich** [comment]
I use Aquamacs 3.6 based on emacs 25.3 and try to install a package that requires emacs 28.1. When will the next Aquamacs come out, that I can use? THANKS
