### ISSUE TITLE
Opening html files from sessions running in Aquamacs

### ISSUE THREAD

**Issue by braunm** [aquamacs-emacs/aquamacs-emacs#151]
Some time after my upgrade to Mojave (I'm now at MacOS 10.14.4), there has been a long delay (6-8 seconds) when a process running in an Aquamacs GUI frame tries to open an html file in any browser.

As a simple example, I have a file, foo.html.  From within Aquamacs, I open a bash shell ( M-x shell) and type `open foo.html`.  There is a long delay before the file opens.  The file opens nearly instantly when called from either the Terminal window directly,  or a Terminal instance of emacs.

Another example is when opening R help files using ESS.  A call to `help("mean")` from an Aquamacs ESS R session results in a long delay, while the same call from R in the Terminal window opens the html help file right away.

I did not have this problem before the Mojave upgrade, and I am stuck as to how to continue to debug this.  Thanks in advance for your help.

Michael Braun

**Comment by treese** [comment]
I have noticed a possibly similar problem: when I start Aquamacs 3.5 (nightly build) on Mojave, the whole system seems to freeze for a while when it starts up. Occasionally when Aquamacs is running this happens again, although I haven't been able to detect a pattern to that.

**Comment by braunm** [comment]
The freezing problem is related to Accessibility options.
In System Preferences > Security and Privacy > Privacy > Accessibility, under "Allow the apps below to control your computer," make sure Aquamacs.app is **not** selected.  I had thought checking that box might have solved my html problem (it did not), but it did cause the system to freeze when either launching Aquamacs, or clicking on the menu bar for the first time.  However, if you uncheck the box, you might have to click on the menu bar twice to use it.

**Comment by treese** [comment]
Fascinating. I turned it off and the freezing disappeared. I would not have guessed that, and I wonder why it actually happens that way. Unfortunately, I have a bunch of Aquamacs functions that call AppleScript, so it looks like I have a choice between getting rid of the startup freezes and losing AppleScript control. Is there something that be done in the Aquamacs app code to work better with Accessibility enabled?

**Comment by braunm** [comment]
An update. It appears the problem is caused by the nightly builds not being signed, and the MacOS trust subsystem not wanting to immediately give access privileges to the browser. The solution is to either sign the nightly builds (if not every night, then after new commits), OR provide instructions to users on how to sign the app themselves. 

Signing the downloaded nightly build is straightforward.

1. If you don't have a certificate for signing apps already, create a self-signed certificate by following the directions at
[https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html). 
Follow the link "To obtain a self-signed certificate using Certificate Assistant”.  After completing those steps, the certificate is now stored in your Keychain.

2. From the Terminal, use codesign to sign the app.
`codesign -s “name_of_the_certificate”  --deep Aquamacs.app`


The external files now open instantly, as they should.

**Comment by davidswelt** [comment]
Michael,
Thanks for diagnosing this.

I will make a proper release as soon as I can.  This will, of course, be signed.  The signing certificate I use is one provided to me by Apple (which I pay for).

Best,
David

**Comment by treese** [comment]
I believe that the signed release of Aquamacs 3.5 fixed this.
