### ISSUE TITLE
aquamacs.org does not support HTTPS

### ISSUE THREAD

**Issue by dlc37** [aquamacs-emacs/aquamacs-emacs#152]
I'd appreciate it if you'd support HTTP over TLS at https://aquamacs.org/

The fact that it uses http://aquamacs.org/download-release.shtml to download a `.dmg` makes it especially concerning. I would prefer an HTTPS site that linked to github for downloads and listed an SHA-256 hash too.

**Comment by davidswelt** [comment]
The URL redirects to Github.
We used to generate a hash for verification, which would be on the general download page at aquamacs.org.
I consider this low priority given that the release code itself is always signed with an Apple-issued developer certificate (which I pay for).

**Comment by davidswelt** [comment]
I have changed this so that the Aquamacs downloads come in via https.

**Comment by treese** [comment]
This was fixed in the earlier conversion of the Aquamacs web site to GitHub pages.
