### ISSUE TITLE
Recent files customization

### ISSUE THREAD

**Issue by bestlem** [aquamacs-emacs/aquamacs-emacs#153]
I would like to add to the files that Recent files ignores.

This should be customizable using recentf-exclude but this does not seem to work in Aquamacs.

If I customize the variable the current two entries get added to the custom list again and again.

If I use setq and also for the customize the problem is that Customizations.el and my init files are read after Recent files are setup (shown in Messages buffer)

How do I change the value of the variable?

A more general issues seems to arise here - should customisations be loaded much earlier in the startup?

**Comment by davidswelt** [comment]
I think these are support questions first.
If a bug report arises, please file one here (for each bug).

**Comment by bestlem** [comment]
If needed I will take up elsewhere
