### ISSUE TITLE
Crash when closing full-screen frame

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#160]
1. full-screen a frame.
2. Command-W to close it.

Crash.

**Comment by davidswelt** [comment]
Applied patch by Alan Third 10/7/2017.  Doesn't help.

**Comment by treese** [comment]
Was the patch from [Emacs bug #26323](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26323)? There's a follow-up discussion [bug#26323: 25.1; Closing frames (in fullscreen) under Mac OS cause immediate crash](https://lists.gnu.org/archive/html/emacs-devel/2018-03/msg00546.html). 

I tried a simple build using the suggested compiler flag, but no joy. It looks like there are enough changes that have happened in the NS code that the most straightforward path is to look at this again after merging more recent core Emacs code, whether that's up through the latest Emacs 25.x or on to 26.

**Comment by davidswelt** [comment]
Interesting.  I can’t check now, but I wonder if we have enabled system tabs.  I guess the check for disabling uses compile-time flag instead of a runtime check (a stupidity that is pervasive throughout the emacs code).

**Comment by treese** [comment]
> On Aug 2, 2019, at 3:23 PM, David Reitter <notifications@github.com> wrote:
> 
> Interesting.  I can’t check now, but I wonder if we have enabled system tabs.  I guess the check for disabling uses compile-time flag instead of a runtime check (a stupidity that is pervasive throughout the emacs code).

Current nsterm.m has this:

/* macOS tabbed windows cause a crash upon closing.
     Aquamacs offers tabs anyway. */
  /* macOS Sierra automatically enables tabbed windows.  We can't
     allow this to be enabled until it's available on a Free system.
     Currently it only happens by accident and is buggy anyway. */
  if ([win respondsToSelector: @selector(setTabbingMode:)])
    [win setTabbingMode: NSWindowTabbingModeDisallowed];

**Comment by davidswelt** [comment]
Ah gee. So I fixed the check and left it in place. I vaguely remember that the tabs were causing crashes.

**Comment by treese** [comment]
Was fixed for 3.5.
