### ISSUE TITLE
Allowing Aquamacs to control computer leads to extermely slow startup

### ISSUE THREAD

**Issue by HayoBaan** [aquamacs-emacs/aquamacs-emacs#162]
When you allow Aquamacs to control your computer in the system preferences (e.g. to prevent having to click twice on some of the menus), startup time of Aquamacs is slowed down considerably. The slowdown is so bad that you can no longer edit new files from the command-line (I guess because the file already got removed before Aquamacs started).

MacOS X Mojave 10.14.6, Aquamacs built from commit https://github.com/davidswelt/aquamacs-emacs/commit/854a9834933fd1fd9fced388cf91c1ec4eeeb7d2 using `flags` build target with `FLAGS='-march=native -mtune=native'`.
System: Mac Book Pro 2019 (32GB, 8-core i9, so plenty fast)

**Comment by davidswelt** [comment]
Is this the same with the 3.4 release, or the 3.5 build available from Aquamacs.org?

**Comment by HayoBaan** [comment]
Hi David,

Interesting; this only seems to be an issue with the version I compiled myself. Any idea what's causing this and what I can do to prevent this when I compile myself?

**Comment by davidswelt** [comment]
No concrete idea, except perhaps compiling with a different SDK.
I hope that a future maintainer of Aquamacs can move it to a better designed and maintained port that does not rely on this kind of nonstandard event handling.

**Comment by HayoBaan** [comment]
It's even weirder: I built a new local version and installed it. Now it starts up fine. However, now the menus don't seem to respond after a first click and the help menu is really slow to show too 😕 

Not sure what's going on here but I guess the system caches some stuff and/or handles things incorrectly which conflicts/leads to weird behaviour sometimes. For example if you move Aquamacs.app from /Applications to another place (e.g. to temporarily test a different version) and then install another version in /Applications, running Aquamacs from the command-line (or with open -a) will call the moved one instead of the one in /Applications…

I'll try to do some more testing to see if I can figure out why I can't use my own compiled version.

**Comment by HayoBaan** [comment]
Additional note: all menu entries take a little while (about 1 sec) to show when you access them for the first time. After that they show quickly, as they should. Guess there's some system overhead induced the first time? This with the nightly build version.

**Comment by davidswelt** [comment]
I’m pretty sure it’s going to be a “won’t fix” for 3.5.  If you’d like to do something highly useful then that would be looking into porting Aquamacs to Yamamoto’s Mac port. The event handling in the old one is messed up.

**Comment by HayoBaan** [comment]
> I’m pretty sure it’s going to be a “won’t fix” for 3.5.  If you’d like to do something highly useful then that would be looking into porting Aquamacs to Yamamoto’s Mac port. The event handling in the old one is messed up.

Hi David, I understand. It's really really weird what's going on here though: I installed the nightly and rebooted and now the slow startup happens with the nightly as well 😖

For a while now, I have been wondering if Aquamacs should not better be rebased on top of the official code, only bringing back the truly “necessary” customizations. Many of the customization you built in the past are no longer necessary for Emacs to run on a Mac and might actually conflict.

My (albeit limited) testing of the “official”, referenced at https://www.gnu.org/software/emacs, release (https://emacsformacosx.com/) showed that the GUI is actually very good (at least on par with Aquamacs). The only thing I really found missing were the keyboard customizations we have grown so accustomed to in Aquamacs, and of course the pre-installed packages. I'm sure there's more customization, but missing the Aquamacs keyboard handling was a showstopper in itself for me so I didn't try any further. 
I could not easily identify the keyboard customizations, but if I could locate those I would like to give this another try. Do you have these somewhere handy?

I also found Yamamoto’s port (https://bitbucket.org/mituharu/emacs-mac/src/master/), but isn't that also just the “official” one, or does it have additional customizations?

**Comment by HayoBaan** [comment]
Note: the “official” code also requests to be able to control the computer.

**Comment by timjervis** [comment]
I have had similar issues of slow Aquamacs startup and slow response to menus for several months, using Aquamacs builds from:

http://jazz.aquamacs.org/~dreitter/Aquamacs/latest/Aquamacs-nightly.tar.bz2

I have the issue on 2 iMacs and 1 MacBook Pro. All three of these machines are running MacOS 10.14.6 right now, but the issue appeared at least back to 10.14.4. I cannot be sure how much further back, but possibly much further back (10.13, 10.12, …).

I am sorry this evidence is so weak and ill-defined.

My workaround so far has been simply to leave Aquamacs up, and avoid the menus.

Tim

**Comment by treese** [comment]
This sounds a lot like the slow behavior that was traced to using unsigned code in the nightly builds (see #151). Might that be the problem?

**Comment by HayoBaan** [comment]
@treese Awesome! That seems to be it (I missed #151 completely as being potentially relevant).
After signing, startup was fast again, however I then suffered unresponsive menus. I decided to remove the permission in security preferences and then request them again in Aquamacs, this fixed that too; menus are now plenty fast. I'll reboot and see if things persist.

Note though that I had to provide my admin password quite a number of times during signing (my user is non-admin and I created the certificate as system certificate, perhaps this was the cause of that)

**Comment by treese** [comment]
@HayoBaan Glad to hear it. The multiple admin prompts seems to be from the --deep signing part of the process, so a lower-level mechanism gets called a lot. I just clicked on the "OK in the future" or whatever button for it, at whatever risk I'm taking on that.

**Comment by HayoBaan** [comment]
@treese Yeah, I figured it was the deep. Didn't get a chance to set “OK in the future” though, I guess because it was needed for admin, not the standard user.

Anyway, just back from a reboot and all seems well. **THANKS!**

Issue can be closed 😃

**Comment by timjervis** [comment]
Yes, thank you! I’ve also signed and re-approved permission in security preferences. I can also report a quick startup and normal menu function.

**Comment by HayoBaan** [comment]
I created pull request #163 with some small modifications to the build script, one of which is emitting a warning that you should sign the code on Mojave.
