### ISSUE TITLE
Failed to verify signature archive-contents.sig

### ISSUE THREAD

**Issue by druimalban** [aquamacs-emacs/aquamacs-emacs#166]
I decided I wanted to fetch a few packages through MELPA. So, I copied the following into ~/Library/Preferences/Aquamacs Emacs/Preferences.el, and made sure to install gnutls:
```
(require 'package)
(with-eval-after-load 'tls
  (push "/private/etc/ssl/cert.pem" gnutls-trustfiles))
(add-to-list 'exec-path "/usr/local/bin")
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(package-initialize)
```
Synchronisation and fetching from MELPA does seem to work. But this subsequently fails to chat to gnu ELPA:

```
Failed to verify signature archive-contents.sig:
No public key for 066DAFCB81E42C40 created at 2019-09-25T10:10:02+0100 using RSA
Command output:
gpg: Signature made Wed 25 Sep 10:10:02 2019 BST
gpg:                using RSA key C433554766D3DDC64221BFAA066DAFCB81E42C40
gpg: Can't check signature: No public key
```

I thought this was related to issues with TLS, but it fails when specifying an http URL for MELPA too. At any rate it seems happy with fetching MELPA. Issue #149 looked similar, but following the steps there (essentially the above) was no help in this respect.

**Comment by rpgoldman** [comment]
There is a recipe for solving this problem:

1. **Temporarily** disable signature checking in package. There's a variable that I *think* is called `package-check-package-signatures`, but I won't swear to it.  Set that using `set-variable` so the change is ephemeral
2. `M-x package-list-packages`
3. Install `gnu-elpa-keyring` package
4. Quit emacs
5. Restart

This is pretty horrible, and it's a *Bad Thing* that we have to do this, but it seems unavoidable.  Maybe we could replace the current Aquamacs build with one that has this package pre-installed to avoid this problem for future users?

**Comment by druimalban** [comment]
I've played around with this quite a bit, but it doesn't seem to work. Here's what I tried:
1. `M-x set-variable RET package-check-signatures RET allow-unsigned`
2. `M-x package-refresh-contents`
It still tries to check signatures on the gnu archive. I'm not sure if that's a bug.
Then, I tried manually importing the `gnu-elpa-keyring-updated` package - but this didn't help either.

**Comment by treese** [comment]
Hi, Duncan. I think you actually need to set package-check-signatures to nil.

**Comment by druimalban** [comment]
Thanks! That worked. Not sure whether to close the issue.

**Comment by treese** [comment]
We'll keep it open for the moment, since there's also a suggestion about releasing an update that deals with this, and I need to think about that.

**Comment by nega0** [comment]
This just bit me w/ vanilla Emacs on Ubuntu, and remembered seeing this issue.  So for documentation sake, the work-arounds are:

- as previously described, temporarily set `package-check-signatures` to `nil`
- add the updated key externally with `gpg --homedir "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/gnupg" --recv-keys 066DAFCB81E42C40`
- remove or hide `gpg` or `gpg2` from your path

I generally don't run GnuPG on my macs, so never hit this issue myself.

**Comment by treese** [comment]
Update ELPA GPG keyring, commit 49134e4feb436f663c3d645872b4c677672f4694.
