### ISSUE TITLE
Aquamacs crashes from arrow key in Save Buffer As dialog box

### ISSUE THREAD

**Issue by treese** [aquamacs-emacs/aquamacs-emacs#168]
From a report to aquamacs-bugs:

> When I try to save the current buffer as something else I get the a regular window with the current file name selected. Pressing the left or right arrow key results in a crash.

I have reproduced it with Aquamacs 3.5 on Mojave.

**Comment by bkinne** [comment]
Same problem on Catalina. When the "Save As" window is pulled down (e.g., via the "Save Buffer As" command), pressing any arrow key causes Aquamacs to crash. This is a very frustrating bug that has caused me to lose work on multiple occasions.

**Comment by treese** [comment]
This is a very common problem, and it shows up in a lot of crash reports.

**Comment by treese** [comment]
Added a workaround to disable special key handling in the dialogs in commit 9d96f4.

**Comment by doccosmos** [comment]
I'm still seeing this on Mac 10.15.7 with: Aquamacs 3.5  GNU Emacs 25.3.50.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G2016))
dated 2019-08-18 rev. 70b7398da506a9a53867909fa12e5cb3a07ba5c9 which claims to be the most recent version available

**Comment by bkinne** [comment]
Still having this problem on Big Sur (11.5.2) with Aquamacs 3.5  GNU Emacs 25.3.50.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G2016)).

**Comment by treese** [comment]
As a followup, I believe this one is fixed in Aquamacs 3.6, which is now available at https://aquamacs.org/downloads/
