### ISSUE TITLE
crash when saving untitled buffers

### ISSUE THREAD

**Issue by nathaniel** [aquamacs-emacs/aquamacs-emacs#17]
I have encountered a crash that occurs reproducibly for Aquamacs 2.0, launched with -q (on 10.5.8).
Steps to reproduce:
Cmd-N
type a few characters of text into the new "untitled" buffer
Cmd-N
type a few characters of text into the new "untitled 2" buffer
Click on "untitled" with mouse
Cmd-S
Save with default Untitled filename, to Desktop (by clicking Desktop in "places" bar in save dialog)
Click on "untitled 2" with mouse
Cmd-S  [--> In some cases, crash occurs here, before dialog appears]
Click Desktop in "places" bar in ave dialog --> crash

I've repeated my steps several times -- I'm not sure what is different, if anything, in cases where the crash occurs before the 2nd Save As dialog appears.

**Comment by davidswelt** [comment]
Can't reproduce in 10.6, so far

**Comment by davidswelt** [comment]
is this still happening?  do we have a trace?  could you run it in gdb?

**Comment by nathaniel** [comment]
It is still happening.  I will post a trace when I have a chance.  Still not at all proficient with GDB, but I'll give it a go.

**Comment by nathaniel** [comment]
Running Aquamacs -q with GDB, below is the error, followed by backtrace.  The error occurs upon Cmd-S on "untitled 2" in the original recipe above.  If you have pointers for debugging further, please let me know!

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000000
0x927e868c in objc_msgSend ()
(gdb) bt
#0  0x927e868c in objc_msgSend ()
#1  0x92c4b1f7 in +[NSMenu(NSKeyEquivalents) _canUseKeyEquivalentForMenuItem:]()
#2  0x92c4aef1 in -[NSMenuItem keyEquivalent]()
#3  0x92d4e863 in -[NSMenuItemCell keyEquivalentAttributedString]()
#4  0x92ca5ebc in -[NSMenuItemCell calcSize]()
#5  0x92ca59a1 in -[NSMenuItemCell drawWithFrame:inView:]()
#6  0x92c8ce6f in -[NSControl drawRect:]()
#7  0x92e936df in -[NSNavNodePopUpButton drawRect:]()
#8  0x92d20bf8 in -[NSView _drawRect:clip:]()
#9  0x92d1f6ef in -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:]()
#10 0x92d1fa86 in -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:]()
#11 0x92d1fa86 in -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:]()
#12 0x92d1fa86 in -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:]()
#13 0x92d1fa86 in -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:]()
#14 0x92d1fa86 in -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:]()
#15 0x92d1e045 in -[NSView _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:]()
#16 0x92d1d987 in -[NSThemeFrame _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:]()
#17 0x92d1a4ab in -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:]()
#18 0x92c5ae7b in -[NSView displayIfNeeded]()
#19 0x92c5aa29 in -[NSWindow displayIfNeeded]()
#20 0x92d16603 in -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:]()
#21 0x92d58567 in -[NSApplication _orderFrontModalWindow:relativeToWindow:]()
#22 0x92d57fd1 in -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:]()
#23 0x92f58eb3 in -[NSSavePanel(NSSavePanelRuntime) beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo:]()
#24 0x92f58cdc in -[NSSavePanel(NSSavePanelRuntime) beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:]()
#25 0x001c08da in Fns_popup_save_panel ()
#26 0x00140996 in Feval ()
#27 0x0013d9bd in funcall_lambda ()
#28 0x00140b49 in apply_lambda ()
#29 0x001406fa in Feval ()
#30 0x001414af in Fif ()
#31 0x001409f8 in Feval ()
#32 0x0013d9bd in funcall_lambda ()
#33 0x0013dc97 in Ffuncall ()
#34 0x0013eac3 in apply1 ()
#35 0x00139fa0 in Fcall_interactively ()
#36 0x0013dff5 in Ffuncall ()
#37 0x0013e189 in call3 ()
#38 0x000cb95d in command_loop_1 ()
#39 0x0013c2ad in internal_condition_case ()
#40 0x000b85a5 in command_loop_2 ()
#41 0x0013c18c in internal_catch ()
#42 0x000c004e in recursive_edit_1 ()
#43 0x000c0204 in Frecursive_edit ()
#44 0x000b792e in main ()
(gdb)

**Comment by davidswelt** [comment]
when you display the save dialog, it should show a special menu with Aquamacs and Edit menu titles.  Do you see that?  Do the menus themselves look incorrect?  The Edit menu should have normal key bindings listed.

I still don't see that crash in 10.6, with the latest Aquamacsen.

**Comment by nathaniel** [comment]
Tested (on a different 10.5.8 machine than my usual) then-current nightly on 9/15 or 9/16:
Save As dialog does show the special menu as described.  Nothing problematic with the menus.  Crash occurs as reported.

**Comment by HayoBaan** [comment]
I can't reproduce this with the latest version of Aquamacs, is this still an issue for you?

**Comment by davidswelt** [comment]
Closing this old issue. Feel free to open with a recipe to reproduce if it is still a problem.
