### ISSUE TITLE
Fullscreen mode: nothing to see, but accepts input

### ISSUE THREAD

**Issue by grossbart** [aquamacs-emacs/aquamacs-emacs#2]
I'm using the Menlon font on Snow Leopard and Aquamacs 2.0preview2. When I try to go into fullscreen mode, the screen stays black, but the buffer receives the input I type (which I see when I go back to normal mode).

**Comment by davidswelt** [comment]
This has been fixed in the master branch (nightly build on the Aquamacs website).
