### ISSUE TITLE
nightlies websites not accessible 

### ISSUE THREAD

**Issue by hevisko** [aquamacs-emacs/aquamacs-emacs#200]
https://groups.google.com/g/aquamacs-devel/c/ncGqwUboyNw refers to http://aquamacs.org/nightlies.shtml and http://beta.aquamacs.org/nightlies.shtml but both websites are not functioning ;(

**Comment by treese** [comment]
In a reworking of the web site, the link was changed to http://aquamacs.org/nightlies.html. Sorry for the confusion!
