### ISSUE TITLE
Wrong documentation/binding gnus-dired-attach

### ISSUE THREAD

**Issue by averter** [aquamacs-emacs/aquamacs-emacs#210]
This [issue](https://github.com/djcb/mu/issues/1896) brought me here. 
`gnus-dired-attach` is, according to the manual, bound to `C-c RET C-a`. However, when looking at the source code of `gnus-dired.el` it is instead bound to `C-c C-m C-a`. The relevant line is
`(define-key map "\C-c\C-m\C-a" 'gnus-dired-attach)`. 
I assume that the keybinding has changed in a recent version, since this only happened when I have updated my OS. Thank you in advance for any info.

**Comment by treese** [comment]
Thanks for the note. `C-m` is the same as the code sent by the return key, so these are two different ways of doing the same thing. To invoke the command, you can type `C-c RET c-a` or `C-c C-m C-a`. 

If they don't work that way, then something more mysterious is going on.

**Comment by averter** [comment]
@treese Thanks for the update. Effectively `C-c RET C-a` doesn't work as expected. Is there any way to debug this? I just receive the message `C-c <return> C-a is undefined`

**Comment by treese** [comment]
@averter What happens when you try it? Does `C-c c-m C-a` do what you expect? Which versions of Aquamacs and MacOS are you using?

**Comment by averter** [comment]
I just receive the message `C-c <return> C-a is undefined`. And yes, `C-c C-m C-a` does the correct thing. I am on gnu-emacs on linux. Does that mean that I should instead be asking this question [here](https://github.com/emacs-mirror/emacs)? Thank you in advance.

**Comment by treese** [comment]
That seems very strange. Since Aquamacs is a version of Emacs for Mac OS, if you are on Linux you might get quicker answers asking elsewhere. https://emacs.stackexchange.com is probably a good place. There's also /r/emacs on Reddit.
