### ISSUE TITLE
Meaningless help for menu functions

### ISSUE THREAD

**Issue by rpgoldman** [aquamacs-emacs/aquamacs-emacs#212]
If I try to get help about a menu item, I get a useless result like this:

<img width="591" alt="Aquamacs menu help" src="https://user-images.githubusercontent.com/3274/107822963-916d5f80-6d44-11eb-884c-9308f09250d3.png">

I'm not sure where these essentially "lambda menus" come from, but they are quite frustrating. I'd be willing to look at trying to fix this myself, but I'm not sure where this is happening.  Some of the menu items give sensible results (like `mac-key-open-file`).

**Comment by treese** [comment]
That does seem pretty pretty annoying! 

Can you describe in a bit more detail what you did? The screenshot looks like it's python-related, but I'm not sure I have all the pieces or the right configuration to look at that. Also, what you tried on the  comparative example for what you did for `mac-key-open-file` would be very helpful. Thanks!

**Comment by rpgoldman** [comment]
@treese Hi. Sorry to have been so long about answering.  As you suspected, I encountered this using the menu for "Virtual Envs" in python mode.  TBQH, I don't know where that comes from -- indeed that was what I was trying to figure out by looking up the keybinding!

It's possible that this is not Aquamacs's fault -- the list of virtual environments that populates this menu is computed from the environment, and maybe it is that process that causes these nameless commands to be created.

Let's close this for now, since I can't find it happening elsewhere. If I do, I will make a better ticket.
