### ISSUE TITLE
PDF-TeX Sync not working with Skim

### ISSUE THREAD

**Issue by frantzen** [aquamacs-emacs/aquamacs-emacs#216]
Hi,

when using the Aquamacs 3.6 Beta together with Skim 1.6.3 the PDF-TeX Sync is not working anymore for me.
Both directions fail, I cannot make Skim view the current location of the buffer, nor can I make Aquamacs show the corresponding location of the PDF.

This was always a bit of a hairy thing for me to setup, so maybe I just need to update my config. What works for me with Aquamacs 3.5 is this setup:

In `/Users/xyz/Library/Preferences/Aquamacs Emacs/customizations.el` I put:
```
(setq TeX-view-program-selection '((output-pdf "PDF Viewer")))
(setq TeX-view-program-list
     '(("PDF Viewer" "/Applications/Skim.app/Contents/SharedSupport/displayline -b -g %n %o %b")))
```

In Skim I set Aquamacs in the settings for PDF-TeX Sync.

To make sync work the first time, it was sometimes necessary to first compile the LaTeX source in Aquamacs once.

Cheers,
Lars

**Comment by frantzen** [comment]
I am using Big Sur.

**Comment by rpgoldman** [comment]
I'm having the same problem, on Catalina. Seems like Preview is always grabbing the requests, instead of Skim.

**Comment by treese** [comment]
Thanks for the report. As @braunm guessed, this is likely related to the bug in AUCTeX configuration he found and reported in #217. Planning to fix it soon, likely in a beta update.

**Comment by treese** [comment]
The AUCTeX loading change has been reverted, and this problem should no longer occur. An updated beta build will be available shortly.
