### ISSUE TITLE
Aquamacs crashes from arrow key in Save Buffer As dialog box still

### ISSUE THREAD

**Issue by RussLaher** [aquamacs-emacs/aquamacs-emacs#222]
This is the same issue as closed ticket #168.  I am opening a new ticket to garner fresh attention to this problem.

Aquamacs 3.5  GNU Emacs 25.3.50.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G2016))
dated 2019-08-18 rev. 70b7398da506a9a53867909fa12e5cb3a07ba5c9
Copyright (C) 2017 Free Software Foundation, Inc.

MacBook Pro laptop
macOS Catalina
Version 10.15.7

Here is how to reproduce the Aquaemacs crash:
1. Click on "New" to open a new buffer
2. Click on "Save" to save buffer to a file.
3. Click on an existing file in File Dialog List to load the filename into the "Save As:" form field, with the aim of modifying it to a different filename for saving (so as to not overwrite the existing file).
4. Press left-arrow key on Mac keyboard
This causes Aquaemacs to crash.

**Comment by treese** [comment]
I believe this one is fixed in Aquamacs 3.6, which is now available at https://aquamacs.org/downloads/
