### ISSUE TITLE
Changed code signature in version 3.6?

### ISSUE THREAD

**Issue by suschizu** [aquamacs-emacs/aquamacs-emacs#227]
Hello! I've received a note that the code signature changed between version 3.5 and 3.6
Can you confirm this? Thanks
`EXPECTED David Reitter (4YEZ374VAY) but FOUND George Treese (DTBC5BX3L9)`

**Comment by treese** [comment]
Thanks for checking. Yes, that is expected. I took over maintaining Aquamacs from David, and my name on the signing certificate is George Treese.

**Comment by suschizu** [comment]
great thanks for the confirmation!
