### ISSUE TITLE
Wrong version or bug?

### ISSUE THREAD

**Issue by fdagnat** [aquamacs-emacs/aquamacs-emacs#230]
Hi,
I installed a fresh aquamacs 3.6 from the web site and I'm a bit puzzled:
- whenever I run check for updates, the small message window state that 3.5 is the aquamacs
- I have searched for a way to check my installed version but I failed (about aquamacs does not print the running version)
So either I run the 3.6 and there is a problem with the check version message or the Aquamacs-3.6.dmg does not contain the right version.

Lastly, perhaps the version number should be printed in the about window.

Have a good day

**Comment by nega0** [comment]
`macOS Menu Bar -> Aquamacs -> Check for Updates...` does indeed state that the latest version is 3.5.

However, when I go to `macOS Menu Bar -> Aquamacs -> About Aquamacs Emacs`, I get a new Aquamacs window titled "About Aquamacs Emacs". (This is the same window/buffer you get when doing `M-x about-emacs`). Contained within is a version string:

```
Aquamacs 3.6  GNU Emacs 25.3.50.1 (x86_64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.6 (Build 20G165))
dated 2021-12-24 rev. 04752ba87a8f3f0677e904e833a1cef8fe38897a
Copyright (C) 2017 Free Software Foundation, Inc.
```

You can also inspect the value of `aquamacs-version` with `C-h v aquamacs-version`.

```
aquamacs-version is a variable defined in ‘site-start.el’.
Its value is "3.6"

Documentation:
A string with Aquamacs’ version number.
The format of the string is undefined.
For a reliable numerical representation, use ‘aquamacs-version-id’.

[back]

```

**Comment by treese** [comment]
Thanks for the report and comments. The version update information from the web site now indicates version 3.6. I had intended to make it possible for some people to update based on the email announcement and then turn on the automated check somewhat later in case problems had started. It looks like that wasn't a great idea, and I won't do it again!

If you are seeing bad version information after this, please reopen the issue.
