### ISSUE TITLE
sub/superscripts

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#26]
Auctex display of subscripts and superscripts no longer works.  On my 10.5 machine, superscripts work but not subscripts,
but on my 10.6 machine, neither do.  Is this an auctex issue or a Cocoa issue perhaps?

**Comment by davidswelt** [comment]
As for sub/superscripts: those work in principle (for me), but the font used is too large.  I found the customization variable `font-latex-script-display' and the customizable face`font-latex-superscript-face'.  Let me know if that helps.

**Comment by davidswelt** [comment]
looks like text with a negative "raise" property is raised, just like text with a positive-valued "raise" property  [NS issue?]

**Comment by HayoBaan** [comment]
Sub & superscripts seem to display fine for me in v3.3, is this still an issue?

**Comment by treese** [comment]
The display in version 3.5 also seems fine, so I am closing this. Let me know if there is a lingering problem.
