### ISSUE TITLE
Osx Key Mode Mouse 3 Behavior / spelling context menu

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#29]
(2) I have "Osx Key Mode Mouse 3 Behavior" customized to "mouse-save-then-kill". However, the popup menu obtained by right-clicking on a word marked as misspelled by "flyspell-buffer  still contains the items of the standard Aquamacs popup menu (in addition to the list of spelling suggestions). This is not consistent.

**Comment by nathaniel** [comment]
fixed.

Commit 01be4ad
