### ISSUE TITLE
Transform to upper or lower case

### ISSUE THREAD

**Issue by grossbart** [aquamacs-emacs/aquamacs-emacs#3]
Emacs has M-l and M-u to transform text to lower, respective upper case. These behave differently from what I expect in that they only work from where the cursor is to the end of the word, whereas I would expect them to work on the whole word the cursor is on.

I think that this would be a sensible default choice and should go into Aquamacs, but maybe it's more of a personal preference or I'm working with the wrong command?

(Also: I didn't find it yet, but if there is a command to titleize a word, I think it should work the same way)

**Comment by davidswelt** [comment]
I think there's a reason for this.  
This would be a topic worth discussing on the aquamacs-devel mailing list.
