### ISSUE TITLE
Scrolling down fails (single-pixel line scroll)

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#31]
From: Meng Xiangliang 911mxl@gmail.com
Date: May 4, 2010 7:30:21 AM EDT
To: aquamacs-bugs@aquamacs.org
Subject: [Aquamacs-bugs] Scrolling not smooth when hl-line-mode is on
Reply-To: Bug reports for Aquamacs Emacs aquamacs-bugs@aquamacs.org

Hi,

I'd like to report a bug in Aquamacs 2.0: Scrolling down with C+N or Down-arrow key is glitchy when global-hl-line-mode is on.

Specifically, when the cursor is at the bottom of the buffer window, pressing Ctrl+N should make the content move up one line and move the cursor to the next line; but sometimes (about 1/3) only the content moved up and the cursor stayed where it was. Scrolling up with Ctrl+P or Up-arrow is ok.

Another strange behavior maybe related is that, when holding down Ctrl+N to scrolling continuously, the cursor sometimes jumps to the middle of the buffer window while it should stays at the bottom.

I'm using the latest nightly build (2010-5-4), and erase all customizations.

**Comment by davidswelt** [comment]
maybe work around this by setting scroll-margin to 2 or 3.

**Comment by davidswelt** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=6264

**Comment by davidswelt** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=6272

**Comment by HayoBaan** [comment]
This doesn't seem to be a problem any longer. At least I can't reproduce it with the latest version of Aquamacs (3.3).
