### ISSUE TITLE
NSSpellChecker suggested spellings reversed in context menu

### ISSUE THREAD

**Issue by nathaniel** [aquamacs-emacs/aquamacs-emacs#34]
Suggestions in context menu, ultimately provided by ns-spellchecker-get-suggestions, are in reverse order relative to the Spelling Panel.  (Order when using ispell-program-name "aspell" is correct, however.)  This could be corrected in lisp but is more properly solved at the ObjC level.

**Comment by davidswelt** [comment]
ns-spellchecker-get-suggestions: sort list in intended order.

Closed by 61e8c9d6970e42e744c0e88f2ce8cf4383bca183
