### ISSUE TITLE
spellchecker: event undefined

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#35]
M-x ispell
Then select "Show Spell-checking panel" from the menu.

Got an error "event undefined".

**Comment by davidswelt** [comment]
<ns-spellchecker-panel-show> undefined.

**Comment by nathaniel** [comment]
The same issue occurs for apparently for all menu commands.  I tested:
Edit-->Spelling-->Show Spelling Panel
Options-->Show Buffers in New Frames
File-->New Buffer in New Frame

It also occurs in Emacs.app 23.1.1 (tested with File-->Open File), so this is not an Aquamacs issue.  I can take a further look at ispell.el to try to figure out what is going on...

**Comment by nathaniel** [comment]
Related: after M-x ispell, C-g does not enter debugger even when "Enter Debugger on Quit/C-g" is checked (set before running ispell).

**Comment by davidswelt** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=6403
