### ISSUE TITLE
spellchecker: hang

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#36]
LaTeX file (change log).  point at \begin{**rawhtml}.
M-x ispell
Tried to open menu -> hang.

I have a SHark file for this.

**Comment by davidswelt** [comment]
turns out this is reproducible for me.
M-x flyspell-buffer works fine.

**Comment by davidswelt** [comment]
Same happening in slightly older version (aquamacs 2.0a).

**Comment by nathaniel** [comment]
Here's the traceback when M-x ispell hangs on changelog.tex, partway through:

Debugger entered--Lisp error: (quit)
  redisplay()
  sit-for(0)
  isearch-lazy-highlight-new-loop(1 7427)
  ispell-highlight-spelling-error-overlay(5896 5902 t)
  ispell-highlight-spelling-error(5896 5902 t)
  ispell-command-loop(("Macron" "Marconi" "Marci" "Margin" "Marlin" "Martin" "Marvin" "Marcia" "Marcie") nil "Marcin" 5896 5902)
  ispell-process-line("^Patch by Marcin Koziej.\n" nil)
  byte-code("b\210\306 \307\306\211\306\310\311!\210)\312\313 \307#\2032

**Comment by davidswelt** [comment]
the loop is produced by xdisp.c:12795, goto too_near_end.
extra_scroll_margin_lines keeps growing.

12639: PT > CHARPOS (startp) does not become true.
scroll_down_p is false.
this_scroll_margin is false
(PT < CHARPOS (scroll_margin_pos)) is also false  (startp.charpos = 1)
w->cursor.vpos is 1, so we don't get "SCROLLING_FAILED", but land in the "else" block

it seems like we haven't scrolled.  (! cursor_row_fully_visible_p (w, extra_scroll_margin_lines <= 1, 0)) is true, and we jump back up.

this_scroll_margin is 0, because scroll_margin is 0.

If I insert a workaround like this one, I can get rid of the hang:

```
  if (! cursor_row_fully_visible_p (w, extra_scroll_margin_lines <= 1, 0))
{
  clear_glyph_matrix (w->desired_matrix);
  ++extra_scroll_margin_lines;
  if (extra_scroll_margin_lines < 1000) // workaround
    goto too_near_end;
}
```

**Comment by davidswelt** [comment]
first call to try_scrolling "SCROLLING_FAILED" is returned
it is called again, and that time scroll_down_p will be nil, PT = 1 (???).
This seems to be not for the main buffer, but for the spelling suggestions:
also:

(gdb) print *current_buffer 
$4 = {
  size = 4611686018427519087, 
  next = 0x1046b95a0, 
  own_text = {
    beg = 0x10321e000 "(0) mast e  (1) master  (2) masts  (3) masse  (4) matte  (5) waste  (6) taste  \n(7) paste  (8) haste  (9) caste  (:) baste  (;) mate  (<) mats  (=) mast  ", 
    gpt = 155, 
    z = 155, 
    gpt_byte = 155, 
    z_byte = 155, 
    gap_size = 1868, 
    modiff = 114, 
    chars_modiff = 114, 
    save_modiff = 1, 
    overlay_modiff = 1, 
    beg_unchanged = 154, 
    end_unchanged = 0, 
    unchanged_modified = 114, 
    overlay_unchanged_modified = 1, 
    intervals = 0x0, 
    markers = 0x102669818, 
    inhibit_shrinking = 0
  }, 
  text = 0x102682c50, 
  pt = 1, 
  pt_byte = 1, 
  begv = 1, 
  begv_byte = 1, 
  zv = 155, 
  zv_byte = 155, 
  base_buffer = 0x0, 
  local_flags = "\000\001", '\0' <repeats 47 times>, 
  modtime = 0, 
  auto_save_modified = 0, 
  display_error_modiff = 0, 
  auto_save_failure_time = -1, 
  last_window_start = 1, 
  clip_changed = 0, 
  newline_cache = 0x0, 
  width_run_cache = 0x0, 
  prevent_redisplay_optimizations_p = 0, 
  overlays_before = 0x0, 
  overlays_after = 0x0, 
  overlay_center = 1, 
  undo_list = 4354776374, 
  name = 4335088289, 
  filename = 4320133130, 
  directory = 4335134545, 
  backed_up = 4320133130, 
  save_length = 0, 
  auto_save_file_name = 4320133130, 
  read_only = 4320133130, 
  mark = 4369129147, 
  local_var_alist = 4430040262, 
  major_mode = 4320133514, 
  mode_name = 4297834689, 
  mode_line_format = 4335840433, 
  header_line_format = 4320819798, 
  keymap = 4320133130, 
  abbrev_table = 4309839005, 
  syntax_table = 4309647981, 
  category_table = 4309649293, 
  case_fold_search = 4320133130, 
  tab_width = 32, 
  fill_column = 280, 
  left_margin = 0, 
  auto_fill_function = 4320133130, 
  buffer_file_type = 4320133130, 
  downcase_table = 4309650909, 
  upcase_table = 4309653565, 
  case_canon_table = 4310060317, 
  case_eqv_table = 4310027069, 
  truncate_lines = 4320133130, 
  word_wrap = 4320133130, 
  ctl_arrow = 4320133226, 
  direction_reversed = 4320133130, 
  selective_display = 4320133130, 
  selective_display_ellipses = 4320133226, 
  minor_modes = 4320133130, 
  overwrite_mode = 4320133130, 
  abbrev_mode = 4320133130, 
  display_table = 4320133130, 
  mark_active = 4320133130, 
  enable_multibyte_characters = 4320133226, 
  buffer_file_coding_system = 4320609690, 
  file_format = 4320133130, 
  auto_save_file_format = 4320133226, 
  cache_long_line_scans = 4320133130, 
  width_table = 4320133130, 
  pt_marker = 4320133130, 
  begv_marker = 4320133130, 
  zv_marker = 4320133130, 
  point_before_scroll = 4320133130, 
  file_truename = 4320133130, 
  invisibility_spec = 4320133226, 
  last_selected_window = 4312941285, 
  display_count = 12, 
  left_margin_cols = 0, 
  right_margin_cols = 0, 
  left_fringe_width = 4320133130, 
  right_fringe_width = 4320133130, 
  fringes_outside_margins = 4320133130, 
  scroll_bar_width = 4320133130, 
  vertical_scroll_bar_type = 4320133226, 
  indicate_empty_lines = 4320133226, 
  indicate_buffer_boundaries = 4320133130, 
  fringe_indicator_alist = 4324207750, 
  fringe_cursor_alist = 4324230982, 
  display_time = 4343568102, 
  scroll_up_aggressively = 4320133130, 
  scroll_down_aggressively = 4320133130, 
  cursor_type = 4300449630, 
  extra_line_spacing = 4320133130, 
  cursor_in_non_selected_windows = 4320133226
}

**Comment by davidswelt** [comment]
i checked in the workaround for now. (1a73d9d)

**Comment by HayoBaan** [comment]
I couldn't reproduce this with Aquamacs 3.3, can it be closed?

**Comment by davidswelt** [comment]
let's close it
