### ISSUE TITLE
aquamacs-delete-other-windows closes frames

### ISSUE THREAD

**Issue by nathaniel** [aquamacs-emacs/aquamacs-emacs#37]
... and has other strange results.  Example case:

start without customizations
Cmd-t three times, to get 4 tabs in initial frame
Cmd-n
Cmd-t three times, to get 4 tabs in new second frame
aquamacs-delete-other-windows (Cmd-Opt-1) causes initial frame to be deleted, and its 4 tabs get added to tabs list in second frame

**Comment by davidswelt** [comment]
this is advertised as "remove splits" in the menu.
I think the function name and its doc string are bad.
The action is OK I think -- it is supposed to merge frames when the current frame has only one window.  This again is wrongly advertised in the menu in that case.

So there's a lot of weird stuff, presumably for historic reasons.

**Comment by davidswelt** [comment]
I'm cleaning this up, but I found that `tabbar-window-merge-windows-in-frame' sometimes did unexpected things (deleting all frames).  I'll try to come up with a test case.

**Comment by nathaniel** [comment]
this function is now missing, though still assigned to A-M-1:
Symbol's function definition is void: aquamacs-delete-other-windows

**Comment by davidswelt** [comment]
bind A-M-1 to the newly named aquamacs-join windows
Closed by 63c3aea8e977815ac666b8c4b37ac25922cc0d20
