### ISSUE TITLE
overflow warning on app start 

### ISSUE THREAD

**Issue by shanbhardwaj** [aquamacs-emacs/aquamacs-emacs#4]
The following warning is displayed when starting aquamacs after a fresh compile. 

Warning (initialization): Building Emacs overflowed pure space.  (See the node Pure Storage in the Lisp manual for details.)

**Comment by davidswelt** [comment]
I don't think this still persists.

**Comment by cmcknight** [comment]
Just did a fresh pull on the 2.4 branch and after compilation got the message above.

Git log:

commit cc48072f43bb43531811197f06e160a245d06ef3
Author: David Reitter david.reitter@gmail.com
Date:   Wed May 30 15:33:35 2012 -0400

```
build script: add /usr/sbin to path for     chown.
GH issue 67
```

**Comment by davidswelt** [comment]
Not sure why you're getting it, but I don't.

Try to do a "make maintainer-clean", then "make install".  That should cause a bootstrap build.
(You make have to run "autoconf", or simply "git reset --hard").
