### ISSUE TITLE
other-frame and next-frame don't cycle

### ISSUE THREAD

**Issue by nathaniel** [aquamacs-emacs/aquamacs-emacs#46]
(other-frame), e.g. as called by Cmd-`, does not _cycle_ through frames as it should; instead, with several frames open, this only flip-flops between the two most recently selected frames.  Ditto for frames returned by next-frame and previous-frame.

These worked properly in the Aquamacs 2.0 release.  (Issue is in recent nightlies)

**Comment by davidswelt** [comment]
The new other/next-frame behavior is correct.  previous-frame (Cmd-~) should, however, cycle, and it does so for me!

**Comment by nathaniel** [comment]
OK, I see that (other-frame -1) = Cmd-~ is cyclic.
But (other-frame) should be cyclic, according to Emacs Manual 23.2:

C-x 5 o  (other-frame)
Select another frame, raise it, and warp the mouse to it. If you repeat this command, it cycles through all the frames on your terminal. 

And from Elisp Reference for v23.2:
The function next-frame lets you cycle conveniently through all the frames on the current display from an arbitrary starting point.

**Comment by nathaniel** [comment]
Correction: since next-frame and previous-frame don't raise or select frames, they're perfectly cyclic until the selected frame is changed.

**Comment by davidswelt** [comment]
It seems that the manual is wrong on several counts.  "Warp the mouse to it", in the Star Trek sense, is not what happens on many window systems.  Maybe it happened that way under X back in 1988.

**Comment by nathaniel** [comment]
The same manual page does explain that Emacs has to be told how to handle the mouse (whether or not to warp).  http://www.gnu.org/software/emacs/manual/html_node/emacs/Frame-Commands.html#Frame-Commands
Regardless of what Emacs ought to do internally, we should have Cmd-` and Cmd-~ cycle opposite directions through all Aquamacs windows, as per standard OS X App behavior.  I do use that feature occasionally, and now I'm missing it!

**Comment by nathaniel** [comment]
Oh.  Now I see this issue is the reverse of #38 -- looks like we can't have both...

**Comment by nathaniel** [comment]
Looks like we had both in 1.9:
Cmd-` and Cmd-~ cycle opposite directions through frames, in order of their last activation;
When a frame is closed, the next most recently focused regains focus.

**Comment by davidswelt** [comment]
provide ns-cycle-frame function and use it in `other-frame'.
Closed by 091878126ae155dfa2f2b69de334d29859fe55ff
