### ISSUE TITLE
Faster initialization

### ISSUE THREAD

**Issue by miggaiowski** [aquamacs-emacs/aquamacs-emacs#50]
Not really a bug, but it turns out to be an issue most of the times I try to quickly edit a file.
Aquamacs is taking an awful long time to open, about 4 to 5 seconds. 

I just took a look at Kod ( http://kodapp.com/ ) and it loads almost instantly. I definitely am not switching, but it would be great if someone could take a look at it and try to speed up Aquamacs loading.

**Comment by davidswelt** [comment]
This has been addressed.
One cannot compare small, compact editors to something like Emacs.
Still, it should launch substantially faster now.
Please open this again if there is further desire for optimization.
