### ISSUE TITLE
.ignore file does not limit load-path

### ISSUE THREAD

**Issue by nathaniel** [aquamacs-emacs/aquamacs-emacs#51]
According to the Aquamacs manual:
If an (emtpy) ﬁle named .ignore exists in a speciﬁc path, Aquamacs does not load any
site-start and site-prestart source ﬁles in this or descending paths and does not add that
or subsequent paths to the load-path.

This isn't working for me.  I used "touch" to create a blank file .ignore in the directory /Library/Application Support/Aquamacs Emacs/Imaxima Plugin/Maxima.app/Contents/, but deeper directories still appear in load-path.

**Comment by nathaniel** [comment]
Looks like .ignore files only work if they are in the "top-level" load path directories: ~/Library/Application Support/Aquamacs Emacs/ or ~/Library/Preferencs/Application Support/Aquamacs Emacs/ etc.
Subdirectories of these are added to load-path by function `normal-top-level-add-subdirs-to-load-path'; this function does work in NOT delving info directories that contain a file ".nosearch".

It seems to me that we should standardize our approach to use EITHER .ignore OR .nosearch.

--N

**Comment by nathaniel** [comment]
Oops -- did not mean to close this issue.  --N

**Comment by nedludd** [comment]
Just ran into this one again.  I was setting up a new Aquamacs and couldn't figure out why libraries in subdirectories were getting loaded automatically...  Then I remembered this.

Here's a vote for standardization on it.

**Comment by davidswelt** [comment]
I'm sorry for not handling this sooner.

Revision 52d4bc addresses the issue by standardizing on .nosearch (following Emacs).
.ignore works as before to ensure backwards-compatibility.

Please have a look at the change and let me know if this fixes the problem for your use case.
