### ISSUE TITLE
Home directory write protected - startup problem

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#52]
From: Marco Bucci marco.bucci@gawab.com
Date: March 5, 2011 3:38:01 PM EST
To: aquamacs-bugs@aquamacs.org
Subject: [Aquamacs-bugs] Version 2.1 fail if home directory is write protected (previous versions not!)
Reply-To: Bug reports for Aquamacs Emacs aquamacs-bugs@aquamacs.org

NOTICE: previous versions till 1.9.1 have not tis problem.

Version 2.1 doen't start correctly (permission denied when try to create ~/.emacs) when the home directory is write protected.

Normally my home is write protected since I hate applications that write there they own files. I had no problem with previous versions, but v2.1 does't work.

Actually there is no reason to let Aquamacs write in the home since it has the appropriate place in /Library/Preferences

---

**Comment by DrDub** [comment]
What do you want to do about this? 

I can see three possibilities:
- Ignore the error and continue (the behavior of previous versions from what is discussed)
- If ~ is write protected then use something else (/tmp/$USER or /Library/Preferences)
- Mark the bug as wontfix

**Comment by davidswelt** [comment]
OP is right in that Aquamacs should not write to ~/ on the Mac.  However, it's a losing proposition to make everything work smoothly, as too many packages assume they can create ~/.foo.config and ~/bar.d.
So, we can't use something else (unless we redefine $HOME, which is not a good idea).

Suggest to leave the warning as is (see below) - this is what it is in the current version.

Closing this issue.

# 

Warning (initialization): Unable to create `user-emacs-directory' (~/.emacs.d/).
Any data that would normally be written there may be lost!
If you never want to see this message again,
customize the variable`user-emacs-directory-warning'.
