### ISSUE TITLE
fullscreen / frame switching interaction

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#54]
As per subject:
1.Open three or more files each with own buffer
2. Observe that cmd-~ cycles through them all
3. Choose one and type cmd-shift-ret to enter full screen mode
4. Observe cmd-~ switches between it and one other only
5 Type cmd-shift-ret when full screen buffer has focus
6 Observe cmd-~ cycles through them all again
7 Observe that the buffer that returned from full screen mode has unreachable white space at the top and the echo area partly out of sight.

The missing echo area matches the white space at the top in size and both seem close to the height of the closed window toolbar.
It is usually possible to recover from this mess by operating the window toolbar show/hide jellybean twice. (In my test I started with the toolbar hidden on each file)

Additionally, with mixed full screen and normal buffers, it is possible to get a tangle where the Apple menu bar is visible when the full screen buffer has focus, obscuring the first line of the contents. I can't write down exactly how I got it tangled, but it involved a few iterations of full and normal screen and changing focus with cmd-~ and by clicking an otherwise unreachable buffer.

I can reproduce this on this Pro 1,1 and a new flavour of MacBook Air

While experimenting on the Air I got Aquamacs so twisted that it failed to close files with cmd-W, but would close 'em with clicking on the red close button, would not respond to cmd-~ at all, would not respond to cmd-Q and had to be force quitted. (I got that frequently enough with 2.1 as well)

Note that I can reproduce this in normal text mode as well as the Python mode shown in this report.

**Comment by treese** [comment]
What I did:
1. Create multiple frames showing different files
2. `Cmd-~` cycles through them
3. `Cmd-shift-RET` to go to full-screen mode
4. `Cmd-~` now has no effect in the full-screen one

I suspect that enough has changed since this that the behavior is different, and it's not clear to me if any changes are needed.

Closing this one for now, but feel free to reopen if there's a lingering problem. Thanks!
