### ISSUE TITLE
de-iconify -> frame hides 

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#55]
Hi,

```
I notice the following unexpected behaviour under MacOS X 10.6.7
```

(though it was also present under 10.6.5 and 10.6.6, and possibly
earlier).  I'm using spaces, with four desktops.

```
When I minimize an Aquamacs window, and later click on the 
```

corresponding icon in the dock to resume editing in the window,
the window frequently opens (animated effect), but as soon as 
the window appears, it vanishes - it's not present as a dock icon, nor
on any desktop.  Aquamacs stays running and doesn't report
any errors; the buffers I was editing are visible in the Window menu.
Selecting any of the buffers in this list for editing appears to do nothing - 
no window appears.   If I create a new buffer in a new frame, I can
continue editing the existing buffers.

```
Thanks, Djun
```

If Emacs crashed, and you have the Emacs process in the gdb debugger,
please include the output from the following gdb commands:
   `bt full' and`xbacktrace'.
For information about debugging Emacs, please read the file
/Applications/Aquamacs.app/Contents/Resources/etc/DEBUG.

In GNU Emacs 23.3.1 (i386-apple-darwin9.8.0, NS apple-appkit-949.54)
of 2011-03-18 on braeburn.aquamacs.org - Aquamacs Distribution 2.2
Windowing system distributor `Apple', version 10.3.1038
configured using`configure  '--with-ns' '--without-x' 'CC=gcc' 'CFLAGS=-O3 -fno-tree-pre -falign-loops -arch i386' 'LDFLAGS=-O3 -fno-tree-pre -falign-loops -arch i386''

Important settings:
 value of $LC_ALL: nil
 value of $LC_COLLATE: nil
 value of $LC_CTYPE: nil
 value of $LC_MESSAGES: nil
 value of $LC_MONETARY: nil
 value of $LC_NUMERIC: nil
 value of $LC_TIME: nil
 value of $LANG: en_CA.UTF-8
 value of $XMODIFIERS: nil
 locale-coding-system: utf-8-unix
 default enable-multibyte-characters: t

Major mode: Text

Minor modes in effect:
 savehist-mode: t
 smart-frame-positioning-mode: t
 aquamacs-autoface-mode: t
 recentf-mode: t
 osx-key-mode: t
 tabbar-mwheel-mode: t
 tabbar-mode: t
 show-paren-mode: t
 delete-selection-mode: t
 pc-selection-mode: t
 cua-mode: t
 tooltip-mode: t
 mouse-wheel-mode: t
 tool-bar-mode: t
 menu-bar-mode: t
 file-name-shadow-mode: t
 global-font-lock-mode: t
 font-lock-mode: t
 blink-cursor-mode: t
 auto-encryption-mode: t
 auto-compression-mode: t
 smart-spacing-mode: t
 column-number-mode: t
 line-number-mode: t
 visual-line-mode: t
 transient-mark-mode: t

Recent input:
N SPC R E A S O N A B L E SPC R E S O U C E SPC L I 
M I ^B ^B ^B ^B ^B ^B ^B R ^B ^B ^B ^B ^B ^B ^B ^B 
^B ^B ^B ^B ^B ^B ^B ^B ^B ^F ^B <escape> D G I V E 
N ^B ^B ^B ^B ^B ^B ^B ^B ^D ^D ^E ^B ^B ^B ^B ^B S 
, SPC ^D ^K W E SPC M U S T SPC P R O C E E D SPC I 
N SPC W E L L - D E F I N E D , SPC P R I O R I T I 
Z E D <return> A N D SPC I N C R E M E N T A L SPC 
S T E P S SPC W H E R E V E R SPC P O S S I L B <backspace> 
<backspace> B L E . ^X ^S ^N ^N ^A ^K ^K ^K ^K ^K ^K 
^K ^P ^P ^P ^P ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F 
^F ^F ^F ^F ^F ^F ^F ^B O N G O I N G , SPC ^F ^F ^F 
^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F 
^F ^F ^F ^F ^B ^B ^B ^B ^B ^B ^B ^B ^B ^B ^B A N D 
SPC <escape> F <escape> D . <escape> D ^D ^X ^S <escape> 
Q ^X ^S ^N ^A ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F ^F I 
N <escape> Q ^X ^S ^N ^N ^N ^X ^S <tool-bar> <open-file> 
⌘S <ns-application-open-untitled> <menu-bar> <help-menu> 
<bug-diagnosis> <send-emacs-bug-report>

Recent messages:
Saving file /Users/djun2/Committees/action-plan...
Wrote /Users/djun2/Committees/action-plan
Auto-saving...done
Saving file /Users/djun2/Committees/action-plan...
Wrote /Users/djun2/Committees/action-plan
Saving file /Users/djun2/Committees/action-plan...
Wrote /Users/djun2/Committees/action-plan
Saving file /Users/djun2/Committees/action-plan...
Wrote /Users/djun2/Committees/action-plan
(No changes need to be saved) [2 times]

Load-path shadows:
/Library/Application Support/Aquamacs Emacs/SLIME/site-start hides /Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/site-start
/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/edit-modes/wikipedia-mode hides /Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/edit-modes/nxhtml/related/wikipedia-mode
/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/edit-modes/php-mode hides /Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/edit-modes/nxhtml/related/php-mode

Features:
(shadow sort mail-extr message ecomplete rfc822 mml mml-sec
password-cache mm-decode mm-bodies mm-encode mailcap mail-parse rfc2231
rfc2047 rfc2045 qp ietf-drums mailabbrev nnheader gnus-util netrc
mm-util mail-prsvr gmm-utils mailheader canlock sha1 hex-util hashcash
mail-utils emacsbug php-mode derived etags ring cc-langs cc-mode
cc-fonts cc-menus cc-cmds cc-styles cc-align cc-engine cc-vars cc-defs
speedbar sb-image ezimage dframe assoc slime-autoloads
load-emacs-plugins aquamacs-mode-defaults auctex-config server
preview-latex tex-site auto-loads aquamacs-aux savehist mouse-sel
one-buffer-one-frame smart-frame-positioning drews_init
color-theme-autoloads saveplace visual-line aquamacs-bug
aquamacs-autoface-mode aquamacs-editing sendmail recentf tree-widget
cus-edit osxkeys emulate-mac-keyboard-mode frame-cmds strings misc-fns
thingatpt+ thingatpt frame-fns avoid aquamacs-mac-fontsets fit-frame
aquamacs-frame-setup aquamacs-tabbar tabbar-window cl cl-19 cus-start
cus-load tabbar easy-mmode warnings load-emacs-pre-plugins
aquamacs-site-start cocoa-compatibility smart-dnd filladapt
aquamacs-redo check-for-updates aquamacs-menu osx_defaults
aquamacs-tool-bar aquamacs mac-extra-functions aquamacs-tools
aquamacs-macros parse-time timezone time-date paren delsel pc-select
cua-base wid-edit regexp-opt advice advice-preload byte-opt bytecomp
byte-compile debug help-fns help-mode view image-file disp-table tooltip
ediff-hook vc-hooks lisp-float-type mwheel ns-win easymenu tool-bar dnd
fontset image fringe lisp-mode register page menu-bar rfn-eshadow timer
select scroll-bar mldrag mouse jit-lock font-lock syntax facemenu
font-core frame cham georgian utf-8-lang misc-lang vietnamese tibetan
thai tai-viet lao korean japanese hebrew greek romanian slovak czech
european ethiopic indian cyrillic chinese case-table epa-hook
jka-cmpr-hook help simple abbrev loaddefs button minibuffer faces
cus-face files text-properties overlay md5 base64 format env code-pages
mule custom widget hashtable-print-readable backquote
make-network-process ns multi-tty emacs)

Command line: (/Applications/Aquamacs.app/Contents/MacOS/Aquamacs)

PATH: /opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/opt/local/bin:/usr/local/mysql/bin:/usr/local/bin:/Users/djun2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/Users/djun2/bin:/usr/X11R6/bin:/sw/bin://sw/lib/ant/bin:/usr/X11R6/bin:/sw/bin://sw/lib/ant/bin:/Users/djun2/bin::/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/opt/local/bin:/usr/local/mysql/bin:/usr/local/bin:/Users/djun2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/X11R6/bin:/sw/bin://sw/lib/ant/bin:/Users/djun2/bin::/usr/texbin

exec-path: (/opt/local/bin /opt/local/sbin /usr/local/mysql/bin /opt/local/bin /usr/local/mysql/bin /usr/local/bin /Users/djun2/bin /usr/bin /bin /usr/sbin /sbin /usr/local/bin /usr/X11/bin /opt/local/bin /opt/local/sbin /usr/local/mysql/bin /Users/djun2/bin /usr/X11R6/bin /sw/bin //sw/lib/ant/bin /usr/X11R6/bin /sw/bin //sw/lib/ant/bin /Users/djun2/bin  /opt/local/bin /opt/local/sbin /usr/local/mysql/bin /opt/local/bin /usr/local/mysql/bin /usr/local/bin /Users/djun2/bin /usr/bin /bin /usr/sbin /sbin /usr/local/bin /usr/X11/bin /usr/X11R6/bin /sw/bin //sw/lib/ant/bin /Users/djun2/bin  . /Applications/Aquamacs.app/Contents/MacOS/bin /usr/texbin)

**Comment by davidswelt** [comment]
Is this still a problem in the current Aquamacs builds?

**Comment by treese** [comment]
I tried various combinations of actions based on the original report, and I couldn't reproduce anything resembling the problem.

**Comment by davidswelt** [comment]
Let's close this as not reproducible.  It probably got fixed at some point.
