### ISSUE TITLE
National characters (right meta+character) not recognised.

### ISSUE THREAD

**Issue by marcinkoziej** [aquamacs-emacs/aquamacs-emacs#58]
Hello, I'm using polish keyboard with national characters entered via right option/meta key. (eg. ą = M-a). What works in Aquamacs stable, under Aquamacs 3.xdev gives:

`⌥ą is undefined`
(It's not even a ⌥a, but ⌥ą)

**Comment by davidswelt** [comment]
Hi,
thanks for your bug report. 

This works perfectly for me in the current 3.x development version.

Could you please give us a list of step-by-step instructions, starting with "Start Aquamacs without customizations" from the "Help/Diagnose and Report Bug" menu.  I also need the keyboard layout settings (Polish? Polish Pro?).

The best way to report bugs is via the Help->Diagnose and Report Bug function.

Thanks
- David

## 

http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by davidswelt** [comment]
Could you please try this out again (and check your settings for the Option key in the Options menu)?
Feel free to reopen this issue in case you still experience difficulties.

**Comment by marcinkoziej** [comment]
Sorry for no reply. I have just downloaded a nightly build and this works perfect.
Thank You for Your great work!!!
