### ISSUE TITLE
OS X 10.7 Lion / Aquamacs 2.3a Crashing

### ISSUE THREAD

**Issue by cmcknight** [aquamacs-emacs/aquamacs-emacs#59]
I am consistently getting a crash  from the 2.3a release under Lion whenever I attempt to use the Command-O key binding to open a file. The sequence I follow is:

   Command-O
   Select a text file
   Select OK
   Dialog closes
   Aquamacs crashes

Interestingly, I can use the standard Emacs C-x C-f and the file opens correctly, leading me to think there may be some issues in the keybindings due to changes in Lion. I'm attempting to debug on my end, but it's hit and miss with regard to my available time to debug.

Regards,

Chuck

**Comment by davidswelt** [comment]
On Aug 6, 2011, at 5:01 PM, cmcknight wrote:

> I am consistently getting a crash  from the 2.3a release under Lion whenever I attempt to use the Command-O key binding to open a file. The sequence I follow is:
> 
>   Command-O
>   Select a text file
>   Select OK
>   Dialog closes
>   Aquamacs crashes
> 
> Interestingly, I can use the standard Emacs C-x C-f and the file opens correctly, leading me to think there may be some issues in the keybindings due to changes in Lion. I'm attempting to debug on my end, but it's hit and miss with regard to my available time to debug.

I don't get this crash on 10.6, so please try to debug.
The current Aquamacs nightly builds (and also the currently available 2.3a binary - it's a new one) have extra debugging info, which makes the crash reports sent upon the next start more informative.  This would be helpful.
- David

**Comment by cmcknight** [comment]
Will do. I didn't get the crash on 10.6 either. I can reduce the test case to just using Command-O. It crashes whether I select a file or not. Will report on what I find.

**Comment by cmcknight** [comment]
Hi David,

I'm trying to build on my laptop over lunch and the build failed. Odd, because it worked on my system at home. Shall I mail the log to you or embed it here?

Thanks!

**Comment by davidswelt** [comment]
Sorry for this simplistic question: Have you tried looking at the error message?

Don't think this is related to this bug, so why not post to the -bugs mailing list, and I'll help you compile there.

**Comment by cmcknight** [comment]
I did, and it said that it couldn't write the __data section which was meaningless to me. I'll continue to dig...

**Comment by davidswelt** [comment]
We had that problem at one point, but it's been fixed.  Which branch are you building?
You may want to try building Aquamacs24 rather than master - does it work then?

**Comment by cmcknight** [comment]
Using Xcode 4.1 / OS X 10.7
1. Clean pull from Github, changed to Aquamacs24 branch. Ensured proper fetch/update/etc.
2. Ran autogen.sh to generate configure file
3. Ran build-aquamacs

Build failed. Last portion of log below (log available if you like):

Loading /Users/cmcknight/github/aquamacs-emacs/lisp/aquamacs/edit-modes/haskell-mode/haskell-site-file.el (source)...
Loading /Users/cmcknight/github/aquamacs-emacs/lisp/aquamacs/check-for-updates.el (source)...
Finding pointers to doc strings...
Finding pointers to doc strings...done
Dumping under the name emacs
--- List of All Regions ---
   address     size prot maxp
--- List of Regions to be Dumped ---
   address     size prot maxp
--- Header Information ---
Magic = 0xfeedfacf
CPUType = 16777223
CPUSubType = -2147483645
FileType = 0x2
NCmds = 23
SizeOfCmds = 3696
Flags = 0x00200085
Highest address of load commands in input file: 0x1006f4000
Lowest offset of all sections in __TEXT segment:   0x24c0
--- List of Load Commands in Input File ---

# cmd              cmdsize name                address     size

0 LC_SEGMENT_64          72 __PAGEZERO                0 0x100000000
1 LC_SEGMENT_64         712 __TEXT           0x100000000 0x1ee000
                           __text           0x1000024c0 0x1a4c94
                           __stubs          0x1001a7154    0x666
                           __stub_helper    0x1001a77bc    0xabc
                           __const          0x1001a8280   0x2a00
                           __cstring        0x1001aac80  0x18bc3
                           __gcc_except_tab 0x1001c3844     0x40
                           __unwind_info    0x1001c3884   0x1d4c
                           __eh_frame       0x1001c55d0  0x28a20
2 LC_SEGMENT_64        1512 __DATA           0x1001ee000 0x458000
                           __program_vars   0x1001ee000     0x28
                           __nl_symbol_ptr  0x1001ee028     0x10
                           __got            0x1001ee038    0x1d0
                           __la_symbol_ptr  0x1001ee208    0x888
                           __objc_classlist 0x1001eea90     0x70
                           __objc_protolist 0x1001eeb00     0x10
                           __objc_imageinfo 0x1001eeb10      0x8
                           __objc_const     0x1001eeb18   0x23e0
                           __objc_selrefs   0x1001f0ef8   0x1130
                           __objc_msgrefs   0x1001f2030     0xf0
                           __objc_classrefs 0x1001f2120    0x218
                           __objc_superrefs 0x1001f2338     0x68
                           __objc_data      0x1001f23a0    0x460
                           __data           0x1001f2800 0x3d5518
                           __const          0x1005c7d20   0x2cc0
                           __cfstring       0x1005ca9e0    0x900
                           __bss            0x1005cb2e0  0x766b0
                           __common         0x1006419a0   0x4581
3 LC_SEGMENT_64          72 __LINKEDIT       0x100646000  0xae000
4 LC_DYLD_INFO_ONLY      48
5 LC_SYMTAB              24
6 LC_DYSYMTAB            80
7 LC_LOAD_DYLINKER       32
8 LC_UUID                24
9 unknown                16
10 LC_UNIXTHREAD         184
11 LC_LOAD_DYLIB          88
12 LC_LOAD_DYLIB          88
13 LC_LOAD_DYLIB          88
14 LC_LOAD_DYLIB          56
15 LC_LOAD_DYLIB          56
16 LC_LOAD_DYLIB          56
17 LC_LOAD_DYLIB          56
18 LC_LOAD_DYLIB         104
19 LC_LOAD_DYLIB         104
20 LC_LOAD_DYLIB         112
21 LC_LOAD_DYLIB          96
22 unknown                16
0x7fc88b8fc080 (sz:   0x3f2d/  0x3f30)
0x7fc88b800000 (sz:  0xfc05e/ 0xfc080)
0x7fc88a5fc080 (sz:   0x3f2d/  0x3f30)
0x7fc88a500000 (sz:  0xfc07a/ 0xfc080)
0x7fc88a4fc080 (sz:   0x3f2d/  0x3f30)
0x7fc88a400000 (sz:  0xfc07f/ 0xfc080)
0x7fc88a6fc080 (sz:   0x3f2c/  0x3f30)
0x7fc88a600000 (sz:  0xfc07f/ 0xfc080)
0x7fc88c7f8000 (sz:   0x32a8/  0x7fa8)
0x7fc88c000000 (sz: 0x327bfe/0x7f8000)
0x7fc88b7f8000 (sz:   0x7fa5/  0x7fa8)
0x7fc88b000000 (sz: 0x7f7ffe/0x7f8000)
0x7fc88d7f8000 (sz:   0x27f4/  0x7fa8)
0x7fc88d000000 (sz: 0x27c9ff/0x7f8000)
0x1026d2000 (sz:        0/  0x1000)
--- Load Commands written to Output File ---
Writing segment __PAGEZERO       @        0 (       0/0x100000000 @          0)
Writing segment __TEXT           @        0 (0x1ee000/0x1ee000 @ 0x100000000)
Writing segment __DATA           @ 0x1ee000 (0x458000/0x458000 @ 0x1001ee000)
        section __program_vars   at 0x1ee000 - 0x1ee028 (sz:     0x28)
        section __nl_symbol_ptr  at 0x1ee028 - 0x1ee038 (sz:     0x10)
        section __got            at 0x1ee038 - 0x1ee208 (sz:    0x1d0)
        sectionunexec: cannot write section __data
 __la_symbol_ptr  at 0x1ee208 - 0x1eea90 (sz:    0x888)
        section __objc_classlist at 0x1eea90 - 0x1eeb00 (sz:     0x70)
        section __objc_protolist at 0x1eeb00 - 0x1eeb10 (sz:     0x10)
        section __objc_imageinfo at 0x1eeb10 - 0x1eeb18 (sz:      0x8)
        section __objc_const     at 0x1eeb18 - 0x1f0ef8 (sz:   0x23e0)
        section __objc_selrefs   at 0x1f0ef8 - 0x1f2028 (sz:   0x1130)
        section __objc_msgrefs   at 0x1f2030 - 0x1f2120 (sz:     0xf0)
        section __objc_classrefs at 0x1f2120 - 0x1f2338 (sz:    0x218)
        section __objc_superrefs at 0x1f2338 - 0x1f23a0 (sz:     0x68)
        section __objc_data      at 0x1f23a0 - 0x1f2800 (sz:    0x460)
make[1]: **\* [bootstrap-emacs] Error 1
make: **\* [src] Error 2

**Comment by cmcknight** [comment]
Did a make clean, forced the use of gcc-4.2 instead of gcc-4.2-llvm. Seems to have resolved the build issue, but not the crash issue. Will try to continue digging into the cause of the crash...

**Comment by davidswelt** [comment]
Any news here?

**Comment by cmcknight** [comment]
Not at this time, work has gotten in the way of my free time.  :-(

**Comment by cmcknight** [comment]
Just pulled and built the latest aquamacs and the crash in the file dialog seems to be gone now.

On Sep 14, 2011, at 9:10 AM, David Reitter wrote:

> Any news here?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/davidswelt/aquamacs-emacs/issues/59#issuecomment-2094798

Chuck McKnight
cmcknight@pheonic.com

"It's cold outside, there's no kind of atmosphere, I'm all alone, more or less, let me fly far away from here, fun, fun, fun, in the sun, sun, sun"  --- Theme Song, Red Dwarf

**Comment by davidswelt** [comment]
I don't reproduce this bug in Lion with the latest build, nor with 2.3a.  People have reported occasional crashes in the file save dialog, and there has been a recent fix to the dialog that I merged, even though that one referred to hangs in very specific, reproducible situations rather than crashes.

You could try this change:

diff --git a/src/nsfns.m b/src/nsfns.m
index 7f67bc8..458c447 100644
--- a/src/nsfns.m
+++ b/src/nsfns.m
@@ -2064,8 +2064,8 @@ Optional arg INIT, if non-nil, provides a default file name to use.  */)
   if (ret)
     fname = build_string ([[panel filename] UTF8String]);
-  [[FRAME_NS_VIEW (SELECTED_FRAME ()) window] makeKeyWindow];
  UNBLOCK_INPUT;
-  [[FRAME_NS_VIEW (SELECTED_FRAME ()) window] makeKeyWindow];
  
  return ret ? fname : Qnil;
  }
