### ISSUE TITLE
Can't customize default face

### ISSUE THREAD

**Issue by kaofelix** [aquamacs-emacs/aquamacs-emacs#6]
I opened Aquamacs without customizations and type M-x customize-face RET default RET to open the customization buffer for the default face. If I try to change background and foreground of the face and save with C-x C-s I get a "Wrong type argument: symbolp, (quote normal)" error. I assume the "normal" symbol came from the Slant property, but even trying to delete it doesn't work.

**Comment by kaofelix** [comment]
Just some extra info I forgot: on the Emacs.app build from http://emacsformacosx.com/ it's working. I started an instance did the same steps and the font color changed.

**Comment by davidswelt** [comment]
nasty one, thanks for catching.  i checked in a fix; details on the aquamacs-bugs mailing list.
