### ISSUE TITLE
Changing font colors on "Font for *-Mode" not working

### ISSUE THREAD

**Issue by kaofelix** [aquamacs-emacs/aquamacs-emacs#7]
Going to menu "Options -> Appearance -> Font for Text-Mode" makes the color dialog appear. Colors shown on text and background buttons are wrong. Text color button show a bright green and background button show white. Changing any of the colors have no effect on the buttons. The background color indeed changes on my opened buffer, but the text color don't. Font changes are applied normally.

**Comment by davidswelt** [comment]
I have fixed the behavior of the color panel after it was opened via the font panel.
Otherwise, when opened directly, the behavior is normal.  You need to drag and drop.
Extra menu items have been added, though. The buttons in the font panel do not change, unfortunately.
