### ISSUE TITLE
Scrolling triggering a backtrace buffer to appear

### ISSUE THREAD

**Issue by cmcknight** [aquamacs-emacs/aquamacs-emacs#70]
Environment:
Mac OS 10.7.4, 8GB RAM, Magic Trackpad, current pull from Github on master

Getting this backtrace when I scroll:

scroll-down()
  byte-code("\301\216 \210)\302\207" [mwheel-scroll-down-function ((byte-code "\300\301 e\"\207" [set-window-start selected-window] 3)) nil] 1)
  mwheel-scroll((triple-wheel-up (#<window 13 on *Backtrace*> 175 (149 . 95) 20487295 nil 175 (13 . 3) nil (6 . 20) (11 . 25)) 4))
  call-interactively(mwheel-scroll nil nil)

**Comment by cmcknight** [comment]
Behaviour appears when scrolling past last or first line in buffer. Investigating further...

**Comment by cmcknight** [comment]
Still no idea. Happens even when I do a fresh clone from github and build. Plain Emacs24 doesn't seem to have that issue (d/led from http://emacsformacosx.com).

**Comment by davidswelt** [comment]
How do you scroll when you do this?  Mouse, keys,  scrollbar?  Which keys?
Have you tried the 3.x build?

Thanks,
David

**Comment by cmcknight** [comment]
I get the effect by using a two-finger gesture on a Magic Trackpad (see config in initial message, although I've now upgraded to Mountain Lion, i.e., 10.8). It occurs when I scroll past the beginning or end of the buffer. Today I rebuilt from both the master and aquamacs24 branches and got the same effect. 

I'm not seeing it in the nightly build, but only when I do a build based on:

git clone git://github.com/davidswelt/aquamacs-emacs.git

I've nuked the directory and I'm doing a fresh pull now to try to understand why I'm seeing this odd behavior.

Best regards,

Chuck

**Comment by cmcknight** [comment]
I removed the ~/Library/Application Support/Aquamacs Emacs directory, then restarted from the current build. The problem seems to have been something in the old settings. I'll report any issues if it reappears when I add back my .emacs customizations, but I'm going to close this issue for now.
