### ISSUE TITLE
aqumacs24 bootstrap fails on MacOS 10.8

### ISSUE THREAD

**Issue by avaranovich** [aquamacs-emacs/aquamacs-emacs#72]
I am building aqumacs24 branch on MacOS 10.8.
Seems the bootstrap process fails. Here are few latest lines I have after I do "make"

Loading site-load.el (source)...
Loading emacs-lisp/easy-mmode...
Loading emacs-lisp/easymenu...
Loading disp-table...
Loading tool-bar...
Warning: Key <tool-bar> already bound to a (prefix) keymap or menu .  Use `define-key' instead.
Loading tooltip...
Loading image...
Loading image-file...
Loading button...
Loading emacs-lisp/cconv...
Loading emacs-lisp/macroexp...
Loading help-fns.el (source)...
Loading emacs-lisp/debug.el (source)...
Eager macro-expansion failure: (error "Attempt to autoload pcase while preparing to dump")
Loading emacs-lisp/bytecomp...
Loading emacs-lisp/byte-opt...
Loading emacs-lisp/advice.el (source)...
(require cl-lib) while preparing to dump
make[2]: **\* [emacs] Error 1
make[1]: **\* [src] Error 2
make: **\* [default] Error 2

**Comment by davidswelt** [comment]
This one's more complicated.  The trick is to remove lisp/site-load.el temporarily for the bootstrap, and then put it back and do another "make". 

A terse message sent from my iPhone.

**Comment by nedludd** [comment]
Can you clarify that a little?  Here's what I did and I'm still get the error:

[after configure, removed 'lisp/site-load.el']
`$ make bootstrap`
[finishes successfully, return 'site-load.el' to 'lisp']

``` bash
$ make
 ....
(require cl-lib) while preparing to dump
make[2]: *** [emacs] Error 1
make[1]: *** [src] Error 2
make: *** [default] Error 2
```

**Comment by davidswelt** [comment]
That's what I thought you should do.  Strange it didn't work.
Do you still have a site-load.elc sitting around?

**Comment by nedludd** [comment]
Nope, no site-load.elc.  Strange.

**Comment by dch** [comment]
FWIW this fix worked fine for me. The instructions for a shallow git checkout to build with emacs 24 on the aquamacs site could be amended; let me know if this is not the right place.

`git clone --depth 3 --branch aquamacs24 git://github.com/davidswelt/aquamacs-emacs.git` i.e. add `--branch aquamacs24`

Many thanks for the port.

**Comment by davidswelt** [comment]
I think I have recently fixed some build problems that should have addressed this.  Could you try again?

**Comment by nedludd** [comment]
Just built branch "aquamacs24" from scratch.  Looks like this is fixed.  Thanks David.
