### ISSUE TITLE
buffer change prompt garbled with ido-mode

### ISSUE THREAD

**Issue by marcinkoziej** [aquamacs-emacs/aquamacs-emacs#74]
Hello. 

Sometimes when i change buffers with ido-mode enabled, the minibuffer prompt is garbled, and displays just: ^X B    {  
(see picture)

http://cloud.lolownia.org/public.php?service=files&file=%2Fmarcin%2Ffiles%2FScreen%20shot%202012-12-03%20at%2001.19.03.png

Choosing alternative buffers with left-right arrows doesn't fix this, the "^X B  {" is still there. The buffer names to choose from are displayed correctly.
Moreover, when I press a key which is not bound, aquamacs will display the message stating it and then will display a proper prompt.

Perhaps anyone could give me a hint of how to debug this?
The ido-read-internal and read-from-minibuffer functions have both a proper "Buffer: " argument, so I believe it's an Auqamacs bug. Perhaps i should attach with gdb, but what to look for?

Regards,

m.

**Comment by davidswelt** [comment]
Closing this old issue.  Feel free to open with a recipe to reproduce if it is still a problem.
