### ISSUE TITLE
Update to Emacs v24

### ISSUE THREAD

**Issue by mcandre** [aquamacs-emacs/aquamacs-emacs#77]
A new Emacs is out, and Marmalade/MELPA packages are starting to require Emacs v24. Could a new Aquamacs be released for the new version?

**Comment by smitty1eGH** [comment]
Could there be a contribution bounty to help this along?

**Comment by mcandre** [comment]
Have you tried [Emacs for Mac OS X](http://emacsformacosx.com/)?

**Comment by davidswelt** [comment]
There already is an Aquamacs based on Emacs 24, and I've been using it for more than a year.
I just never considered Aquamacs 3.x ready for "release", even though we're getting close.

You can download it at http://aquamacs.org/nightlies.shtml

**Comment by davidswelt** [comment]
And, please, help identify and address remaining issues in Aquamacs 3.x!

**Comment by mcandre** [comment]
I'm happy with `brew install emacs --cocoa` myself. I just thought it would be nice for noobs if Aquamacs were compatible with all the cool Emacs v24 plugins that are out now.

**Comment by davidswelt** [comment]
We are very close to a regular release based on Emacs 24.  In fact, the main download on aquamacs.org is already Aquamacs 3.0 (preview 1).
