### ISSUE TITLE
Aquamacs Distribution 3.xdev: Freezes and Crashes

### ISSUE THREAD

**Issue by mattsears** [aquamacs-emacs/aquamacs-emacs#78]
Hey there,

Using the latest nightly development build and Aquamacs 3.x and it randomly crashes and occasionally freezes (most often when TAB'ing and while in IDO mode).    Here is my emacs config:

[mattsears/emacs](https://github.com/mattsears/emacs) 

Any ideas what could be causing this?

Thanks!

**Comment by davidswelt** [comment]
Closing, unresolved, but probably no longer an issue.
