### ISSUE TITLE
git checkout aquamacs24

### ISSUE THREAD

**Issue by lawlist** [aquamacs-emacs/aquamacs-emacs#79]
I haven't been able to figure out how to use the terminal to download just the latest source for building my own latest version (similar to emacs-trunk) of Aquamacs 24.  I'm assuming that pressing the ZIP button on this webpage is what I am trying to do with the terminal:

https://github.com/davidswelt/aquamacs-emacs/tree/aquamacs24

Checking out does not work with this code (branch not recognized):

$ git clone --depth 3 git://github.com/davidswelt/aquamacs-emacs.git
$ cd aquamacs-emacs
$ git checkout aquamacs24

If we add the -b option to the first line of code, it appears to download the entire 1.58 GB master.  However, checkout works if I do that -- but I'm not certain how to separate it to build my own latest Aquamacs24 release (Intel OSX).

If we use $ git clone git://github.com/davidswelt/aquamacs-emacs.git , then the entire master is also downloaded.

Would it be possible for anyone to please spoon feed me with the correct terminal lines of code to download the source for the latest version of Aqumacs24 (similar to emacs-trunk)?

**Comment by davidswelt** [comment]
I think what's happening is: Your local branch references are yours.  aquamacs24 is remote after you clone it.  See here:

http://stackoverflow.com/questions/67699/how-do-i-clone-all-remote-branches-with-git

**Comment by lawlist** [comment]
Thank you -- that helped.  I successfully cloned the Aquamacs24 branch.  For anyone just wanting to build the Aquamacs24 latest bleeding edge version (like the emacs-trunk), it doesn't look like the .git sub-folder (weighing in at a whopping 1.38GB) is needed.

Is the 182.5MB ZIP download option from the git webpage for Aquamacs24 always up to date and the same as cloning the branch?

**Comment by davidswelt** [comment]
If it doesn't come with the .git folder, it will definitely not be the same as cloning the branch.

But it should be up to date with respect to building the app (see Github documentation please) - and it may be similar to a git clone --depth 1.

**Comment by lawlist** [comment]
Ah . . . I suspected the git website was doing something magical by creating the ZIP option.  So for building the latest release, there are two (2) options:  Use the ZIP download option of the Aquamacs24 branch; or, clone the branch and pull the updates.  I am really enjoying learning more about Aquamacs and Emacs -- thank you very much -- greatly appreciated !!!
