### ISSUE TITLE
find-function doesn't work for Aquamacs functions

### ISSUE THREAD

**Issue by kaofelix** [aquamacs-emacs/aquamacs-emacs#8]
Doing M-x find-function RET new-empty-buffer-other-frame causes the following message to appear:
ad-Orig-error: Can't find library /Applications/Aquamacs.app/Contents/Resources/lisp/../site-lisp/aquamacs.el

I've tested with emacs default functions (info, for instance) and it works properly. It seems to only affect aquamacs functions.

**Comment by davidswelt** [comment]
OK, I just committed a fix.   Thanks - keep the good bug reports coming!
