### ISSUE TITLE
ad-handle-definition: `desktop-read' got redefined

### ISSUE THREAD

**Issue by lawlist** [aquamacs-emacs/aquamacs-emacs#80]
Nothing major, but I just wanted to report that the latest aquamacs24 branch results in the following error after building with the basic pre-configured setup on OSX Mountain Lion:

ad-handle-definition: `desktop-read' got redefined

The following custom set variable seems to quiet the error:

 '(revive-desktop-after-launching (quote (quote never)))

On a positive note, it looks like F11 is crashing the application less frequently.

I realize this is developmental and I just wanted to participate in some small way because I really enjoy using Aquamacs and customizing it has been a wonderful learning experience for me.

**Comment by treese** [comment]
Thanks for the report. This does not seem to happen out-of-the-box with Aquamacs 3.5. If it recurs, please reopen this.
