### ISSUE TITLE
Aquamacs24 -- Make Bootstrap Fails on Snow Leopard

### ISSUE THREAD

**Issue by lawlist** [aquamacs-emacs/aquamacs-emacs#82]
The latest version of Aquamcs 24 fails on Make Bootstrap on Snow Leopard

. . .

-o temacs  dispnew.o frame.o scroll.o xdisp.o menu.o  window.o charset.o coding.o category.o ccl.o character.o chartab.o bidi.o cm.o term.o terminal.o xfaces.o    emacs.o keyboard.o macros.o keymap.o sysdep.o buffer.o filelock.o insdel.o marker.o minibuf.o fileio.o dired.o cmds.o casetab.o casefiddle.o indent.o search.o regex.o undo.o alloc.o data.o doc.o editfns.o callint.o eval.o floatfns.o fns.o font.o print.o lread.o syntax.o unexmacosx.o bytecode.o process.o gnutls.o callproc.o region-cache.o sound.o atimer.o doprnt.o intervals.o textprop.o composite.o xml.o inotify.o profiler.o       fontset.o fringe.o image.o nsterm.o nsfns.o nsmenu.o nsselect.o nsimage.o nsfont.o terminfo.o lastfile.o      ../lib/libgnu.a                        -lncurses         -lpthread   \

Undefined symbols:
  "_OBJC_CLASS_$_WebView", referenced from:
      __objc_classrefs__DATA@0 in nsfns.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make[2]: **\* [temacs] Error 1
make[1]: **\* [src] Error 2
make: **\* [bootstrap] Error 2
MBP:aquamacs24 HOME$

**Comment by davidswelt** [comment]
The nightly build seems to work fine.
I recall fixing a few merge issues w.r.t. WebView and associated frameworks.

Try "make maintainer-clean" before doing a "make bootstrap".
- David

**Comment by lawlist** [comment]
I added make maintainer-clean to my list of steps to build aquamacs24 on Snow Leopard and it looks like the errors begin around the nsterm.m section.  I am using Tower.app to pull the most recent updates for the aquamacs24 branch, and then I am highlighting all files in the Browse window, and right-clicking to save all 37 items highlighted to the temporary directory for building (e.g., /tmp) and running the following commands on OSX 10.6.8:

./autogen/copy_autogen

./configure --with-ns

make maintainer-clean

make bootstrap

. . .

---

In the meantime, I'm going to try the Github zip download option and build from that and see if I get the same error:

https://github.com/davidswelt/aquamacs-emacs/archive/aquamacs24.zip

---

-O2   nsterm.m
nsterm.m: In function ‘ns_redraw_scroll_bars’:
nsterm.m:2069: warning: multiple methods named ‘-display’ found
/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:258: warning: using ‘-(void)display’
/System/Library/Frameworks/WebKit.framework/Headers/DOMCSS.h:138: warning: also found ‘-(NSString *)display’
nsterm.m: In function ‘ns_draw_fringe_bitmap’:
nsterm.m:2376: warning: implicit declaration of function ‘window_header_line_inhibited_p’
nsterm.m: In function ‘ns_draw_glyph_string’:
nsterm.m:3371: warning: assignment makes integer from pointer without a cast
nsterm.m: In function ‘ns_create_terminal’:
nsterm.m:4206: warning: assignment from incompatible pointer type
nsterm.m: In function ‘-[EmacsApp savePanelDidEnd2:returnCode:contextInfo:]’:
nsterm.m:4926: warning: implicit declaration of function ‘ns_update_menubar’
nsterm.m: In function ‘-[EmacsApp applicationDidFinishLaunching:]’:
nsterm.m:4983: warning: no ‘-invalidateRestorableState’ method found
nsterm.m:4983: warning: (Messages without a matching method signature
nsterm.m:4983: warning: will be assumed to return ‘id’ and accept
nsterm.m:4983: warning: ‘...’ as arguments.)
nsterm.m: In function ‘-[EmacsApp encodeRestorableStateWithCoder:]’:
nsterm.m:5075: warning: ‘NSApplication’ may not respond to ‘-encodeRestorableStateWithCoder:’
nsterm.m: In function ‘-[EmacsView windowDidExitFullScreen:]’:
nsterm.m:6852: warning: ‘EmacsView’ may not respond to ‘-updateCollectionBehaviour’
nsterm.m: In function ‘-[EmacsView toggleFullScreen:]’:
nsterm.m:6911: warning: ‘NSWindow’ may not respond to ‘-toggleFullScreen:’
gcc -std=gnu99 -c  -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/nsfns.d -MP    -g3 -O2   nsfns.m
nsfns.m: In function ‘Fns_cycle_frame’:
nsfns.m:1411: warning: no ‘-_cycleWindowsReversed:’ method found
nsfns.m:1411: warning: (Messages without a matching method signature
nsfns.m:1411: warning: will be assumed to return ‘id’ and accept
nsfns.m:1411: warning: ‘...’ as arguments.)
nsfns.m: In function ‘Fns_popup_save_panel’:
nsfns.m:2046: warning: implicit declaration of function ‘ns_update_menubar’
nsfns.m: In function ‘ns_run_ascript’:
nsfns.m:2724: warning: comparison between pointer and integer
nsfns.m:2726: warning: assignment makes pointer from integer without a cast
nsfns.m: In function ‘Fns_do_applescript’:
nsfns.m:2778: warning: comparison between pointer and integer
nsfns.m: At top level:
nsfns.m:3793: warning: incomplete implementation of class ‘EmacsSavePanel’
nsfns.m:3793: warning: method definition for ‘-runPanel’ not found
nsfns.m: In function ‘syms_of_nsfns’:
nsfns.m:3975: warning: assignment makes pointer from integer without a cast
gcc -std=gnu99 -c  -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/nsmenu.d -MP    -g3 -O2   nsmenu.m
nsmenu.m: In function ‘ns_update_menubar’:
nsmenu.m:452: warning: multiple methods named ‘-clear’ found
/System/Library/Frameworks/QuartzCore.framework/Headers/CIImageAccumulator.h:46: warning: using ‘-(void)clear’
/System/Library/Frameworks/WebKit.framework/Headers/DOMCSS.h:116: warning: also found ‘-(NSString *)clear’
nsmenu.m:480: warning: passing argument 1 of ‘addSubmenuWithTitle:forFrame:’ discards qualifiers from pointer target type
nsmenu.m: In function ‘-[EmacsToolbar addDisplayItemWithImage:idx:helpText:enabled:visible:key:labelText:]’:
nsmenu.m:1520: warning: ‘stringWithCString:’ is deprecated (declared at /System/Library/Frameworks/Foundation.framework/Headers/NSString.h:386)
nsmenu.m:1521: warning: ‘stringWithCString:’ is deprecated (declared at /System/Library/Frameworks/Foundation.framework/Headers/NSString.h:386)
nsmenu.m: In function ‘pop_down_menu’:
nsmenu.m:1767: warning: incompatible Objective-C types initializing ‘struct EmacsAlertPanel *’, expected ‘struct EmacsDialogPanel *’
gcc -std=gnu99 -c  -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/nsselect.d -MP    -g3 -O2   nsselect.m
gcc -std=gnu99 -c  -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/nsimage.d -MP    -g3 -O2   nsimage.m
nsimage.m: In function ‘ns_image_width’:
nsimage.m:135: warning: multiple methods named ‘-size’ found
/System/Library/Frameworks/AppKit.framework/Headers/NSDockTile.h:36: warning: using ‘-(NSSize)size’
/System/Library/Frameworks/WebKit.framework/Headers/DOMHTMLSelectElement.h:49: warning: also found ‘-(int)size’
/System/Library/Frameworks/WebKit.framework/Headers/DOMCSS.h:250: warning: also found ‘-(NSString *)size’
nsimage.m: In function ‘ns_image_height’:
nsimage.m:152: warning: multiple methods named ‘-size’ found
/System/Library/Frameworks/AppKit.framework/Headers/NSDockTile.h:36: warning: using ‘-(NSSize)size’
/System/Library/Frameworks/WebKit.framework/Headers/DOMHTMLSelectElement.h:49: warning: also found ‘-(int)size’
/System/Library/Frameworks/WebKit.framework/Headers/DOMCSS.h:250: warning: also found ‘-(NSString *)size’
nsimage.m: In function ‘+[EmacsImage allocInitFromFile:]’:
nsimage.m:267: warning: ‘bestRepresentationForDevice:’ is deprecated (declared at /System/Library/Frameworks/AppKit.framework/Headers/NSImage.h:128)
gcc -std=gnu99 -c  -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/nsfont.d -MP    -g3 -O2   nsfont.m
nsfont.m: In function ‘nsfont_open’:
nsfont.m:932: warning: ‘CGFontCreateWithPlatformFont’ is deprecated (declared at /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Headers/CGFont.h:60)
gcc -std=gnu99 -c  -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/terminfo.d -MP    -g3 -O2  terminfo.c
gcc -std=gnu99 -c  -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/lastfile.d -MP    -g3 -O2  lastfile.c
gcc -std=gnu99 -Demacs  -I. -I/Users/HOME/Desktop/aquamacs24/src -I../lib -I/Users/HOME/Desktop/aquamacs24/src/../lib                 -MMD -MF deps/.d -MP    -g3 -O2  -fno-pie -prebind -framework AppKit -framework IOKit -framework Quartz -Xlinker -headerpad -Xlinker 6C8  \
      -o temacs  dispnew.o frame.o scroll.o xdisp.o menu.o  window.o charset.o coding.o category.o ccl.o character.o chartab.o bidi.o cm.o term.o terminal.o xfaces.o    emacs.o keyboard.o macros.o keymap.o sysdep.o buffer.o filelock.o insdel.o marker.o minibuf.o fileio.o dired.o cmds.o casetab.o casefiddle.o indent.o search.o regex.o undo.o alloc.o data.o doc.o editfns.o callint.o eval.o floatfns.o fns.o font.o print.o lread.o syntax.o unexmacosx.o bytecode.o process.o gnutls.o callproc.o region-cache.o sound.o atimer.o doprnt.o intervals.o textprop.o composite.o xml.o inotify.o profiler.o       fontset.o fringe.o image.o nsterm.o nsfns.o nsmenu.o nsselect.o nsimage.o nsfont.o terminfo.o lastfile.o      ../lib/libgnu.a                        -lncurses         -lpthread   \

Undefined symbols:
  "_OBJC_CLASS_$_WebView", referenced from:
      __objc_classrefs__DATA@0 in nsfns.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make[3]: **\* [temacs] Error 1
make[2]: **\* [src] Error 2
make[1]: **\* [bootstrap] Error 2
make: **\* [bootstrap] Error 2
MBP:aquamacs24 HOME$

**Comment by davidswelt** [comment]
Unlikely to be an issue with the checkout.  Does it work with the real autotools, rather than copy-autogen?
—
A terse message sent with my phone

**Comment by lawlist** [comment]
I tried a few weeks ago to figure out how to use autogen.sh, but I was never able to find a good article on Google -- I only found references to a bug that affects it and someone wrote that this is the reason the copy-autogen was included as a workaround to the bug.  Here is the autogen.sh error on Snow Leopard:

Checking whether you have the necessary tools...
(Read INSTALL.BZR for more details on building Emacs)

Checking for autoconf (need at least version 2.65)...
ok
Checking for automake (need at least version 1.11)...
ok
Your system has the required tools, running autoreconf...
configure.ac:24: error: Autoconf version 2.65 or higher is required
configure.ac:24: the top level
autom4te: /usr/bin/gm4 failed with exit status: 63
aclocal: /usr/bin/autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
MBP:aquamacs24 HOME$ ./autogen.sh

**Comment by davidswelt** [comment]
This is the relevant change.  Make sure you have the "libs_nsgui" bit in configure.ac and configure.

diff --git a/configure.ac b/configure.ac
index a52e252..f2dbc6d 100644
--- a/configure.ac
+++ b/configure.ac
@@ -4244,13 +4244,14 @@ case "$opsys" in
    ## The -headerpad option tells ld (see man page) to leave room at the
    ## end of the header for adding load commands.  Needed for dumping.
    ## 0x690 is the total size of 30 segment load commands (at 56
-   ## each); under Cocoa 31 commands are required.
-   ## each); under Cocoa 33 commands are required.
-   ## 96F - 45 load commands
  if test "$HAVE_NS" = "yes"; then
    libs_nsgui="-framework AppKit"
    if test "$NS_IMPL_COCOA" = "yes"; then
-        libs_nsgui="$libs_nsgui -framework IOKit"
-        libs_nsgui="$libs_nsgui -framework IOKit -framework Quartz -framework Webkit"
    fi
-     headerpad_extra=6C8
-     headerpad_extra=96F
  else
    libs_nsgui=
    headerpad_extra=690

**Comment by lawlist** [comment]
Thanks -- I'll have an opportunity to try it out later tonight and I'll report back . . . .

**Comment by lawlist** [comment]
Steps taken in an effort to apply proposed patch:

*\* Copy the following to a flat file and label it as aquamacs24.patch, and place it in the root directory of the aquamacs24 branch:

```
diff --git a/configure.ac b/configure.ac 
index a52e252..f2dbc6d 100644 
--- a/configure.ac 
+++ b/configure.ac 
@@ -4244,13 +4244,14 @@ case "$opsys" in 
## The -headerpad option tells ld (see man page) to leave room at the 
## end of the header for adding load commands. Needed for dumping. 
## 0x690 is the total size of 30 segment load commands (at 56 
- ## each); under Cocoa 31 commands are required. 
+ ## each); under Cocoa 33 commands are required. 
+ ## 96F - 45 load commands 
if test "$HAVE_NS" = "yes"; then 
libs_nsgui="-framework AppKit" 
if test "$NS_IMPL_COCOA" = "yes"; then 
- libs_nsgui="$libs_nsgui -framework IOKit" 
+ libs_nsgui="$libs_nsgui -framework IOKit -framework Quartz -framework Webkit" 
fi 
- headerpad_extra=6C8 
+ headerpad_extra=96F 
else 
libs_nsgui= 
headerpad_extra=690
```

*\* From the root directory of the aquamacs24 branch, run the following command from the terminal:

MBP:aquamacs24 HOME$ /usr/bin/patch -Np1 < aquamacs24.patch
patching file configure.ac
/usr/bin/patch: ***\* malformed patch at line 12: if test "$HAVE_NS" = "yes"; then 

MBP:aquamacs24 HOME$ patch -p1 < aquamacs24.patch
patching file configure.ac
patch: ***\* malformed patch at line 12: if test "$HAVE_NS" = "yes"; then 

MBP:aquamacs24 HOME$

**Comment by lawlist** [comment]
With respect to OSX 10.6.8 (Snow Leopard), I removed and reinstalled automake and autoconf.  Building the latest branch of aquamacs24 now works well with autogen.sh:

```
./autogen.sh

./configure --with-ns

make bootstrap

make && make install
```

Thanks for your help.
