### ISSUE TITLE
Aquamacs opens new frame on rightmost monitor

### ISSUE THREAD

**Issue by krono** [aquamacs-emacs/aquamacs-emacs#87]
[aquamacs24 branch, c3057fd5093d242ce5dc587ba28a57c1867e811f]

I have a multimonitor setup.

Creating a new frame (eg, with cmd-n) creates a new frame, but on the rightmost monitor of all my attached ones (main MBP monitor and two additional).

Also: sometimes switching to the minibuffer (find-file, M-x) moves the current frame to the rightmost window, with no trace why (not in _Messages_ or the System console)

**Comment by davidswelt** [comment]
The second point has been addressed.

**Comment by krono** [comment]
Yes, I can confirm and I am incredibly happy about that :+1:

**Comment by davidswelt** [comment]
As for the first point, can you check whether it's working any better now?  It should create new frames near the selected frame.

**Comment by krono** [comment]
I will, once I am near a second monitor again.

**Comment by krono** [comment]
All works well now. I think this can safely be closed.
