### ISSUE TITLE
Buffers not being repainted, sometimes

### ISSUE THREAD

**Issue by timjervis** [aquamacs-emacs/aquamacs-emacs#89]
Aquamacs is not always repainting the buffer on my platform. The frequency of the problem varies from rare, c. 1 / 10 minutes, to frequent when every key press in the mini-buffer leaves the mini-buffer blank (i.e. the session is effectively unusable).

A work-around is to issue the command "M-x redraw-display" when the buffer is not repainted, but this is not so helpful when the issue is with the mini-buffer.

The issue appears to be the same as that reported here:

  http://stackoverflow.com/questions/16039813/emacs-wont-repaint-buffer-windows-7

My hardware platform is a MacBook Pro Retina, Mid 2012:

  Model Name:   MacBook Pro
  Model Identifier: MacBookPro10,1
  Processor Name:   Intel Core i7
  Processor Speed:  2.7 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 8 MB
  Memory:   16 GB
  Boot ROM Version: MBP101.00EE.B02
  SMC Version (system): 2.3f36

Software:
  OS X 10.9 (13A603)

**Comment by davidswelt** [comment]
Tim,
Thanks for bringing this up.  I see it, too, but have been unable to diagnose it. 
You could help greatly with this by working out a reproducible test case, starting from an Aquamacs without customizations.

After that, we will need to reproduce with GNU Emacs (I can help with that).  

Once we have a reproducible test case in Emacs, I can pretty much guarantee that it'll be fixed.
- David

## 

http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by davidswelt** [comment]
I mostly notice this when opening a second window in the frame with C-x 2.

**Comment by timjervis** [comment]
I have been looking out for a pattern but I'm sorry to say I have little to add at this point.

I wondered if it was connected with general load on the CPU at one point. Running a parallel make of 11 scribble to PDF runs occasionally causes it, but not reliably.

It seems to go in phases such that sometimes almost every frame operation exhibits the problem (find-file-in-other-window or switch to buffer in other window), while at others there isn't a problem.

I've noticed it during regexp-replaces too, but again, it seems to go in phases where sometimes there's no problem, and others it's so bad it needs a restart. After a restart, things seem to be fine again. Related to memory management perhaps?

On 31 Dec 2013, at 20:42, David Reitter notifications@github.com wrote:

> I mostly notice this when opening a second window in the frame with C-x 2.
> 
> —
> Reply to this email directly or view it on GitHub.

Tim Jervis

http://timjervis.com/

**Comment by davidswelt** [comment]
The pattern is that the cursor is on a tab when you enter the minibuffer.
Bugfix to follow.

**Comment by timjervis** [comment]
Except that for me, I don't use tabs and have them hidden to maximise the area available for text...

Tim Jervis
+44 7801 337 078

**Comment by davidswelt** [comment]
I meant tab characters in the buffer.  I have commited a change that fixes the bug for my specific test case.  Perhaps you can download the nightly build (it's ready now) and report back if the bug is fixed.  I'm going to keep this issue open until I hear back.

**Comment by timjervis** [comment]
Thanks David, I'll do that and let you know.

On 8 Jan 2014, at 01:02, David Reitter notifications@github.com wrote:

> I meant tab characters in the buffer. I have commited a change that fixes the bug for my specific test case. Perhaps you can download the nightly build (it's ready now) and report back if the bug is fixed. I'm going to keep this issue open until I hear back.
> 
> —
> Reply to this email directly or view it on GitHub.

Tim Jervis

http://timjervis.com/

**Comment by davidswelt** [comment]
Just make sure you're getting the newly built binary.  (Check the timestamp). 

—
A terse message sent with my phone

**Comment by timjervis** [comment]
I have 8th January 2014 01:02 (I'm in London, UK)

On 8 Jan 2014, at 01:08, David Reitter notifications@github.com wrote:

> Just make sure you're getting the newly built binary.  (Check the timestamp).  
> 
> — 
> A terse message sent with my phone 
> 
> On Tue, Jan 7, 2014 at 8:07 PM, Tim Jervis notifications@github.com 
> wrote: 
> 
> > Thanks David, I'll do that and let you know. 
> > On 8 Jan 2014, at 01:02, David Reitter notifications@github.com wrote: 
> > 
> > > I meant tab characters in the buffer. I have commited a change that fixes the bug for my specific test case. Perhaps you can download the nightly build (it's ready now) and report back if the bug is fixed. I'm going to keep this issue open until I hear back. 
> > > 
> > > — 
> > > Reply to this email directly or view it on GitHub. 
> > > 
> > > Tim Jervis 
> > > 
> > > ## http://timjervis.com/ 
> > > 
> > > Reply to this email directly or view it on GitHub: 
> > > https://github.com/davidswelt/aquamacs-emacs/issues/89#issuecomment-31797023
> > > —
> > > Reply to this email directly or view it on GitHub.

Tim Jervis

http://timjervis.com/

**Comment by davidswelt** [comment]
I think that's good.  The server is on GMT/UTC. 

—
A terse message sent with my phone

**Comment by timjervis** [comment]
I've not had a repeat of the repaint issue since this release. By no means an exhaustive test, but I would have expected many repaint issues every day otherwise.

On 8 Jan 2014, at 01:46, David Reitter notifications@github.com wrote:

> I think that's good.  The server is on GMT/UTC.  
> 
> — 
> A terse message sent with my phone 
> 
> On Tue, Jan 7, 2014 at 8:12 PM, Tim Jervis notifications@github.com 
> wrote: 
> 
> > I have 8th January 2014 01:02 (I'm in London, UK) 
> > On 8 Jan 2014, at 01:08, David Reitter notifications@github.com wrote: 
> > 
> > > Just make sure you're getting the newly built binary. (Check the timestamp). 
> > > 
> > > — 
> > > A terse message sent with my phone 
> > > 
> > > On Tue, Jan 7, 2014 at 8:07 PM, Tim Jervis notifications@github.com 
> > > wrote: 
> > > 
> > > > Thanks David, I'll do that and let you know. 
> > > > On 8 Jan 2014, at 01:02, David Reitter notifications@github.com wrote: 
> > > > 
> > > > > I meant tab characters in the buffer. I have commited a change that fixes the bug for my specific test case. Perhaps you can download the nightly build (it's ready now) and report back if the bug is fixed. I'm going to keep this issue open until I hear back. 
> > > > > 
> > > > > — 
> > > > > Reply to this email directly or view it on GitHub. 
> > > > > 
> > > > > Tim Jervis 
> > > > > 
> > > > > ## http://timjervis.com/ 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub: 
> > > > > https://github.com/davidswelt/aquamacs-emacs/issues/89#issuecomment-31797023 
> > > > > — 
> > > > > Reply to this email directly or view it on GitHub. 
> > > 
> > > Tim Jervis 
> > > 
> > > ## http://timjervis.com/ 
> > > 
> > > Reply to this email directly or view it on GitHub: 
> > > https://github.com/davidswelt/aquamacs-emacs/issues/89#issuecomment-31797276
> > > —
> > > Reply to this email directly or view it on GitHub.

Tim Jervis

http://timjervis.com/

**Comment by davidswelt** [comment]
OK, thanks for your the update.  I am closing this bug.
