### ISSUE TITLE
Cannot install Command Line Tools

### ISSUE THREAD

**Issue by Behinder** [aquamacs-emacs/aquamacs-emacs#90]
on 10.8.5 AQ previev 3 - when I click in menu "instal command line tools" i got only message in footer than I need to run aquamacs from console but when I do this there is command not found. Restarting terminal - and the same. Shel ZSH.

**Comment by davidswelt** [comment]
Yes, I fixed this one just this morning:

aeeaed11a8c9a8efac5d08b4b872b81951b991fb

Stay tuned for the next preview release.
