### ISSUE TITLE
background drawing in left prefix area

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#94]
From: Konrad Podczeck 
Subject: [aquamacs-devel] A misbehaviour when making selection
Date: January 13, 2014 at 10:25:11 AM EST

I just noticed the follwing. Start Aquamacs without customizations, open a file with "long" lines. Switch on linum mode. Make a selection by dragging the mouse. During dragging you see that on the parts of long line that are wrapped just into visual lines, the selection extends to the left of the left fringe. In GNu emacs this does not happen.

Konrad

**Comment by treese** [comment]
This does not appear to happen in Aquamacs 3.5. Closing this issue; if it recurs, please reopen it.
