### ISSUE TITLE
Present toolbar implementation causes flickering when opening new frames

### ISSUE THREAD

**Issue by podczeck** [aquamacs-emacs/aquamacs-emacs#95]
When new frames are opened, you may observe a flickering: drastically in GNU emacs, to a much smaller amount in Aquamacs with the new animation feature. In both GNU emacs and Aquamacs, this flickering completely disappears if, in default-frame-alist, one sets (tool-bar-lines 0).

In fact, in GNU emacs one may see at a closer look the following when a new frame is opened: First the new frame is drawn with text-field in the frame as if there would be new toolbar, and only after this the toolbar is loaded and the text-field is redrawn to make room for the toolbar. This explains why there is no flickering with (tool-bar-lines 0).

This seems as if the necessary room for the toolbar is calculated too late by emacs. The order should be reversed:  First calculate for the toolbar, and only thereafter draw the frame. If this order is not possible, the frame should stay invisible until all calculations are done.

**Comment by davidswelt** [comment]
I have applied two fixes from upstream: df42aae1819b0a1fcfc12a2e07dd9230a2331a91 and 90116338c46664f30e8bcc75993b236c7fe99d12.

**Comment by davidswelt** [comment]
I cannot reproduce this at all, neither before, nor after these changes.

**Comment by podczeck** [comment]
To reproduce: take the recent nightly build, which does not have the fix. With this build, start Aquamacs without customizations. Swich "Show Tabs" off and " Show Buffers in New Frames" on. Open any buffer. Now repeatedly do C-x 5 2. If you don't see the flickering, open another file, then again repeatedly do C-x 5 2. You will recognize it, sooner or later.

Here a description in the words of Jan Djärv:

"It is an extra redraw that happens only on NS, i.e. frame is fully drawn, then cleared then redrawn again."

Am 01.04.2014 um 23:30 schrieb David Reitter:

**Comment by treese** [comment]
I tried to reproduce this on my 2016 MacBook Pro, running Mojave. Between toolbar and non-toolbar frames, there seems be a tiny pause in the rendering, but not a flickering that seems weird or annoying.

Things may have changed enough since the original report that there's not the same kind of problem as reported. If it's still there, please reopen this issue.
