### ISSUE TITLE
file locks retained

### ISSUE THREAD

**Issue by davidswelt** [aquamacs-emacs/aquamacs-emacs#96]
I’ve noticed some odd behaviour in Aquamacs 3.0 GNU Emacs 24.3.50.2 (x86_64-apple-darwin13.0.0, NS apple-appkit-1265.00) of 2014-01-19 (Aquamacs-3.0) on watson.  It has to do with external drives.

Say I visit a file in an external drive.  After editing it, I save it and delete the buffer.  (The command list-buffers does not show the file.)  I then try to eject the external drive and it fails saying that Aquamacs is accessing it.  ???  I can only eject (without forcing it) after quitting Aquamacs, which is not optimal.

Am I missing something?

Thanks,
    José

**Comment by treese** [comment]
I could not reproduce this with Aquamacs 3.5.
