### ISSUE TITLE
3.1 has no permission for Preferences folder?

### ISSUE THREAD

**Issue by xenzo** [aquamacs-emacs/aquamacs-emacs#99]
it cannot make not only "~/Library/Preferences/Aquamacs Emacs" but "/Library/Preferences/Aquamacs Emacs"

**Comment by maehne** [comment]
I observed the same error message on a fresh install of OS X Yosemite. As a workaround, I had to create the folders manually.

**Comment by davidswelt** [comment]
I think this has been addressed with version 3.1a.  Please re-open if you still encounter this issue.
